### ISSUE TITLE
Loop rebooting with docker

### ISSUE THREAD

**Issue by monsieurpouet** [gotify/server#109]
Hi !

I've a little issue (I guess) with my yaml file.
I've created a docker-compose file with that:

```
version: '3'

services:
    gotify:
        image: gotify/server
        ports:
                - '127.0.0.1:2083:443'
        volumes:
                - /etc/gotify:/app/data
        restart: always
        environment:
                - GOTIFY_SERVER_SSL_ENABLED=true
                - GOTIFY_SERVER_SSL_REDIRECTTOHTTPS=true
                - GOTIFY_SERVER_SSL_PORT=443
                - GOTIFY_SERVER_SSL_LETSENCRYPT_ENABLED=false
                - GOTIFY_SERVER_SSL_LETSENCRYPT_ACCEPTTOS=false
                - GOTIFY_SERVER_SSL_LETSENCRYPT_CACHE=certs
                - GOTIFY_SERVER_SSL_LETSENCRYPT_HOSTS=- push.blabla.fr
                - GOTIFY_DATABASE_DIALECT=sqlite3
                - GOTIFY_DATABASE_CONNECTION=gotify.db
                - GOTIFY_DEFAULTUSER_NAME=monsieurpouet
                - GOTIFY_DEFAULTUSER_PASS=blabla
                - GOTIFY_UPLOADEDIMAGESDIR=images
```

But, when I launch my docker-compose, I see, in my docker logs, this error.
And my container, reboot constatly.

> Starting Gotify version 1.2.1@2018-12-12-21:08:19
> Started Listening on port 443
> Started Listening on port 80
> open : no such file or directory

Any ideas perhaps ?
