### ISSUE TITLE
Proxy error with docker

### ISSUE THREAD

**Issue by monsieurpouet** [gotify/server#113]
Hi,

Now, Gotify works in my docker container.
But, I've a reverse proxy with my apache2. Sadly, I've a 502 Proxy Error.
The is my VH:

```
<VirtualHost *:80>                                                                
        ServerName push.blabla.fr                                               
        Redirect / https://push.blabla.fr/                                      
        ServerSignature Off                                                       
        #RewriteEngine on                                                         
        #RewriteCond %{SERVER_NAME} =push.blabla.fr                             
        #RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]  
</VirtualHost>                                                                    
                                                                                  
<VirtualHost *:443>                                                               
        ServerName push.blabla.fr                                               
        SSLEngine On                                                              
        ProxyPass "/" http://127.0.0.1:2083/ retry=0 timeout=5                    
        ProxyPassReverse / http://127.0.0.1:2083/                                 
        ServerSignature Off                                                       
                                                                                  
        CustomLog /var/log/apache2/blabla_access.log combined                       
        ErrorLog /var/log/apache2/blabla_error.log                                  
                                                                                  
        Include /etc/letsencrypt/options-ssl-apache.conf                          
        Include /etc/letsencrypt/options-ssl-apache.conf                          
        SSLCertificateFile /etc/letsencrypt/live/push.blabla.fr/fullchain.pem   
        SSLCertificateKeyFile /etc/letsencrypt/live/push.blabla.fr/privkey.pem  
</VirtualHost>        
```                                               

Does anybody a idea ?

**Comment by jmattheis** [comment]
Hey @monsieurpouet 

is there any gotify/server log when you try to connect to gotify/server through the apache2 proxy? 
This [serverfault answer](https://serverfault.com/questions/185894/proxy-error-502-reason-error-reading-from-remote-server-with-apache-2-2-3-de) suggests adding `Keepalive=On` to the ProxyPass parameters could you try this?

**Comment by monsieurpouet** [comment]
I'm sorry, I had forgot some logs.
My Gotify Logs:

```
Starting Gotify version 1.2.1@2018-12-12-21:08:19
Started Listening on port 443
Started Listening on port 80
http: TLS handshake error from 172.24.0.1:34828: tls: first record does not look like a TLS handshake
http: TLS handshake error from 172.24.0.1:34832: tls: first record does not look like a TLS handshake
http: TLS handshake error from 172.24.0.1:34856: tls: first record does not look like a TLS handshake
http: TLS handshake error from 172.24.0.1:34860: tls: first record does not look like a TLS handshake
http: TLS handshake error from 172.24.0.1:34866: tls: first record does not look like a TLS handshake
http: TLS handshake error from 172.24.0.1:39092: tls: first record does not look like a TLS handshake
http: TLS handshake error from 172.24.0.1:39288: tls: first record does not look like a TLS handshake
http: TLS handshake error from 172.24.0.1:41954: tls: first record does not look like a TLS handshake
http: TLS handshake error from 172.24.0.1:41958: tls: first record does not look like a TLS handshake
```

I put a KeepAlive directive in my conf file. But, I've same error.

**Comment by eternal-flame-AD** [comment]
Looks like Apache send a plain HTTP request to the gotify TLS endpoint. Make sure you have set `GOTIFY_SERVER_PORT` to `2083` as shown on you apache configuration and set `GOTIFY_SERVER_SSL_ENABLED=false`

It would be good to post both your gotify config and apache config so that we can have a better overview of your configuration:)

**Comment by eternal-flame-AD** [comment]
The `ports` should be `127.0.0.1:2083:2083`, as you should be connecting to port `2083` instead of `443` in your container.

Your docker-compose in whole should be:
```
version: '3'

services:
    gotify:
        image: gotify/server
        ports:
                - '127.0.0.1:2083:2083'
        volumes:
                - /etc/gotify:/app/data
        environment:
                - GOTIFY_SERVER_PORT=2083
                - GOTIFY_SERVER_SSL_ENABLED=false
                - GOTIFY_SERVER_SSL_REDIRECTTOHTTPS=true
                - GOTIFY_SERVER_SSL_PORT=443
                - GOTIFY_SERVER_SSL_LETSENCRYPT_ENABLED=true
                - GOTIFY_SERVER_SSL_LETSENCRYPT_ACCEPTTOS=false
                - GOTIFY_SERVER_SSL_LETSENCRYPT_CACHE=certs
                - GOTIFY_SERVER_SSL_LETSENCRYPT_HOSTS=- push.blabla.fr
                - GOTIFY_DATABASE_DIALECT=sqlite3
                - GOTIFY_DATABASE_CONNECTION=gotify.db
                - GOTIFY_DEFAULTUSER_NAME=admin
                - GOTIFY_DEFAULTUSER_PASS=pass
                - GOTIFY_UPLOADEDIMAGESDIR=images
```
