### ISSUE TITLE
How to use letsencrypt option

### ISSUE THREAD

**Issue by dazzag24** [gotify/server#148]
Hi,

Really interesting project!  So thanks for uploading.  I'm trying to set it up on a low cost scaleway.com instance.  Its works in HTTP mode, but I'm stuck on getting the letsencrypt config to work.

Relevant changes to my config file:

```
server:
  listenaddr: "" # the address to bind on, leave empty to bind on all addresses
  port: 8080 # the port the HTTP server will listen on

  ssl:
    enabled: true # if https should be enabled
    redirecttohttps: true # redirect to https if site is accessed by http
    listenaddr: "" # the address to bind on, leave empty to bind on all addresses
    port: 443 # the https port
    certfile: # the cert file (leave empty when using letsencrypt)
    certkey: # the cert key (leave empty when using letsencrypt)
    letsencrypt:
      enabled: true # if the certificate should be requested from letsencrypt
      accepttos: true # if you accept the tos from letsencrypt
      cache: data/certs # the directory of the cache from letsencrypt
      hosts: # the hosts for which letsencrypt should request certificates
      - redacted.com
<snip>
```

Output from running gotify:

```
Starting Gotify version 2.0.2@2019-03-10-10:10:51
Started Listening for TLS connection on :443
Started Listening for plain HTTP connection on :8080
http: TLS handshake error from 82.24.250.128:59162: acme/autocert: unable to authorize "redacted.com"; challenge "tls-alpn-01" failed with error: acme: authorization error for redacted.com: 403 urn:acme:error:unauthorized: Cannot negotiate ALPN protocol "acme-tls/1" for tls-alpn-01 challenge; challenge "http-01" failed with error: acme: authorization error for redacted.com: 403 urn:acme:error:unauthorized: Invalid response from http://redacted.com/.well-known/acme-challenge/Dc_5hTlsRkepPjAFCtm7AeDyQJ-gtZq-tpPXwnqWIms [51.15.52.182]: 504
http: TLS handshake error from 82.24.250.128:59160: acme/autocert: missing certificate
http: TLS handshake error from 82.24.250.128:59174: acme/autocert: missing certificate
http: TLS handshake error from 82.24.250.128:59164: EOF
http: TLS handshake error from 82.24.250.128:59324: acme/autocert: missing certificate
http: TLS handshake error from 82.24.250.128:59322: acme/autocert: missing certificate
http: TLS handshake error from 82.24.250.128:59328: acme/autocert: missing certificate
http: TLS handshake error from 82.24.250.128:59326: EOF
```
it looks as if the challenge is attempting to connect to port 80 (which is already being used by another process) whereas I've configured gotify to use port 8080 for http.

Thanks
