### ISSUE TITLE
Setup in Lamp Server

### ISSUE THREAD

**Issue by mskian** [gotify/server#153]
Hi,
I Just install this on Lamp server via Docker Image
some live sites are there

while running this below command 

```bash
docker run -p 8080:8080 -v /var/gotify/data:/app/data gotify/server
```

I got this below errors

```
docker: Error response from daemon: driver failed programming external connectivity on endpoint laughing_liskov 
```
```
 Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use.
```

**Comment by eternal-flame-AD** [comment]
Seems like a docker issue, the docker daemon is having difficulty setting up port forwarding? I tried your command both on my machine and play-with-docker, neither way did I successfully reproduce the error. 

BTW, the docker image defaults to listen on port 80 in the container. So if you want to expose this at 8080 on your host machine, you need to use `-p 8080:80` or specify a [custom configuration](https://gotify.net/docs/config).

Would you please test out whether your docker installation is correct by testing out other images that require port exposure, or test it out on another server?

**Comment by eternal-flame-AD** [comment]
Would you please provide some context on when the two errors you provided has shown up? Did you see the gotify version information show up before these errors or something else happened? Please provide a transcript of what happened on the terminal between the docker run command and the final error.

**Comment by mskian** [comment]
@eternal-flame-AD 


docker run -p 80:80 -v /var/gotify/data:/app/data gotify/server

```
docker: Error response from daemon: driver failed programming external connectivity on endpoint naughty_kilby (a40471c918b8e8384de8d49426dbdfd35bac8fe7b2e39bdc616b30093e36d86e): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use.
```

`config.yml` we need to create this manually ?

**Comment by mskian** [comment]
After changing the port to `8080:80`
but currently, I access it via <MYSERVERIP>:8080 
while login I get this error
```
websocket: request origin not allowed by Upgrader.CheckOrigin
```

**Comment by eternal-flame-AD** [comment]
If you want to define custom behavior you can create it manually, but it should not fail to start without a config file.

I am pretty sure that it is a docker problem. Check these: `(I) port 80 on your host machine is not already in use (II)your docker daemon is run as root `. If it all seems fine, I think you will need to ask for help in the docker community:)

**Comment by eternal-flame-AD** [comment]
This is a known issue and will be fixed in #150. Current workaround is to set an environment variable to explicitly allow the origin of your websocket request:

```
docker run -e GOTIFY_SERVER_STREAM_ALLOWEDORIGINS="- \".your.server.tld\""
```

**Comment by mskian** [comment]
how to run this permanently on the server

**Comment by eternal-flame-AD** [comment]
What does "this" refers to? You mean to start gotify on device startup or keep the environment variable persistent?

**Comment by mskian** [comment]
means run permanently on the domain push.example.com

**Comment by eternal-flame-AD** [comment]
You can refer to [this](https://docs.docker.com/config/containers/start-containers-automatically/#restart-policy-details) docker documentation on how to keep your container running. I think `--restart always` is what you want:)

**Comment by mskian** [comment]
How to Validate Let's Encrypt currently my port is `8080`

**Comment by eternal-flame-AD** [comment]
See the description in #148, you need to expose port 80 directly to use LE.

I recommend joining the [community chat](https://matrix.to/#/#gotify:matrix.org) for detailed help on server setup, configuration, etc.:)

**Comment by mskian** [comment]
I am Successfully setup site working on both www and non-www

non-www conf

`example.conf`

```
<VirtualHost *:80>
	# The ServerName directive sets the request scheme, hostname and port that
	# the server uses to identify itself. This is used when creating
	# redirection URLs. In the context of virtual hosts, the ServerName
	# specifies what hostname must appear in the request's Host: header to
	# match this virtual host. For the default virtual host (this file) this
	# value is not decisive as it is used as a last resort host regardless.
	# However, you must set it for any further virtual host explicitly.
	
	ServerName push.example.com
	ServerAdmin webmaster@localhost
	DocumentRoot /var/gotify/data

	Keepalive On

    # Proxy web socket requests to /stream
    ProxyPass "/stream" ws://127.0.0.1:8080/ retry=0 timeout=5
    # Proxy all other requests to /
    ProxyPass "/" http://127.0.0.1:8080/ retry=0 timeout=5
    ProxyPassReverse / http://127.0.0.1:8080/

	# Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
	# error, crit, alert, emerg.
	# It is also possible to configure the loglevel for particular
	# modules, e.g.
	#LogLevel info ssl:warn

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

	# For most configuration files from conf-available/, which are
	# enabled or disabled at a global level, it is possible to
	# include a line for only one particular virtual host. For example the
	# following line enables the CGI configuration for this host only
	# after it has been globally disabled with "a2disconf".
	#Include conf-available/serve-cgi-bin.conf

</VirtualHost>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
```

`example-le-ssl.conf`

```
<IfModule mod_ssl.c>
<VirtualHost *:443>
	# The ServerName directive sets the request scheme, hostname and port that
	# the server uses to identify itself. This is used when creating
	# redirection URLs. In the context of virtual hosts, the ServerName
	# specifies what hostname must appear in the request's Host: header to
	# match this virtual host. For the default virtual host (this file) this
	# value is not decisive as it is used as a last resort host regardless.
	# However, you must set it for any further virtual host explicitly.
	
	ServerName push.example.com
	ServerAdmin webmaster@localhost
	DocumentRoot /var/gotify/data

	Keepalive On

    # Proxy web socket requests to /stream
    ProxyPass "/stream" ws://127.0.0.1:8080/ retry=0 timeout=5
    # Proxy all other requests to /
    ProxyPass "/" http://127.0.0.1:8080/ retry=0 timeout=5
    ProxyPassReverse / http://127.0.0.1:8080/

	# Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
	# error, crit, alert, emerg.
	# It is also possible to configure the loglevel for particular
	# modules, e.g.
	#LogLevel info ssl:warn

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

	# For most configuration files from conf-available/, which are
	# enabled or disabled at a global level, it is possible to
	# include a line for only one particular virtual host. For example the
	# following line enables the CGI configuration for this host only
	# after it has been globally disabled with "a2disconf".
	#Include conf-available/serve-cgi-bin.conf

SSLCertificateFile /etc/letsencrypt/live/push.example.com/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/push.example.com/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>
```

My Gotify configuration

```
# Example configuration file for the server.
# Save it to `config.yml` when edited

server:
  listenaddr: "" # the address to bind on, leave empty to bind on all addresses
  port: 8080:80 # the port the HTTP server will listen on

  ssl:
    enabled: true # if https should be enabled
    redirecttohttps: true # redirect to https if site is accessed by http
    listenaddr: "" # the address to bind on, leave empty to bind on all addresses
    port: 443 # the https port
    certfile: # the cert file (leave empty when using letsencrypt)
    certkey: # the cert key (leave empty when using letsencrypt)
    letsencrypt:
      enabled: true # if the certificate should be requested from letsencrypt
      accepttos: true # if you accept the tos from letsencrypt
      cache: data/certs # the directory of the cache from letsencrypt
      hosts: # the hosts for which letsencrypt should request certificates
      - push.example.com
  
  responseheaders: # response headers are added to every response (default: none)
    Access-Control-Allow-Origin: "*"
    Access-Control-Allow-Methods: "GET,POST"

  stream:
    allowedorigins: # allowed origins for websocket connections (same origin is always allowed)
      - ".+.example.com"

database: # for database see (configure database section)
  dialect: sqlite3
  connection: /var/gotify/data/gotify.db

defaultuser: # on database creation, gotify creates an admin user
  name: admin # the username of the default user
  pass: admin # the password of the default user
passstrength: 10 # the bcrypt password strength (higher = better but also slower)
uploadedimagesdir: /var/gotify/data/images # the directory for storing uploaded images
pluginsdir: /var/gotify/data/plugins # the directory where plugin resides
```

Everything this working perfectly including SSL
but I need Help in Docker to run this forever
