### ISSUE TITLE
Connect MYSQL

### ISSUE THREAD

**Issue by mskian** [gotify/server#175]
Hi I have little bit confusion in `config.yml` setup
I want to connect MYSQL instead of SQLite
I created a File on /etc/gotify/ location

```
docker run -p 8080:80 -v "`pwd`:/etc/gotify/" -v /var/gotify/data:/app/data gotify/server
```
Outptut
```
panic: dial tcp 127.0.0.1:3306: connect: connection refused

goroutine 1 [running]:
main.main()
	/proj/app.go:47 +0x4bb

```
```
gotify:DBPASS@/gotifydb?charset=utf8&parseTime=True&loc=Local
```

**Comment by mskian** [comment]
@eternal-flame-AD 

```
gotify:DBPASS@/gotifydb?charset=utf8&parseTime=True&loc=Local
```
is this correct format ?

**Comment by eternal-flame-AD** [comment]
Where is your MYSQL server running at? In docker container network, `127.0.0.1` can only be used to connect to the container itself, not the docker host.

**Comment by eternal-flame-AD** [comment]
The format is correct, the error message indicates that the application cannot talk to your MYSQL server with the given address. If you need to use docker maybe you should refer to [this](https://docs.docker.com/network/) for more help on how to configure the network of your gotify server container so that it can reach your MYSQL server.

**Comment by mskian** [comment]
Not running in Docker network 
I am confused 
we need to setup  Docker network for mysql right?

**Comment by eternal-flame-AD** [comment]
> Where is your MYSQL server running at?

Please answer this question first.

The docker network is by default bridged with the host, so if your MYSQL is running in your host computer or another container, the default `127.0.0.1` won't work.

**Comment by mskian** [comment]
@eternal-flame-AD  
I am using Lamp Stack
yes running on my server

**Comment by eternal-flame-AD** [comment]
Then you will need to find out the gateway address to your container.

First `docker container ls` to see your container ID.
```bash
$ docker container ls
CONTAINER ID        IMAGE                             COMMAND             CREATED             STATUS              PORTS               NAMES
58e553fcf0e0        gotify/build:1.12.0-linux-amd64   "/bin/bash"         18 minutes ago      Up 18 minutes                           sharp_varahamihira
```
Then run `docker container inspect $CONTAINER_ID`
```bash
$ docker container inspect 58e553fcf0e0 | jq ".[0].NetworkSettings.Networks"
{
  "bridge": {
    "IPAMConfig": null,
    "Links": null,
    "Aliases": null,
    "NetworkID": "75d58701816a1e847760c61261ddc1c06f9873252f9de2be02e09011c0d32986",
    "EndpointID": "db203ad05e04b614c0a067c96bb6467c18892fc829378fd7addcd249f615a258",
    "Gateway": "172.17.0.1",
    "IPAddress": "172.17.0.2",
    "IPPrefixLen": 16,
    "IPv6Gateway": "",
    "GlobalIPv6Address": "",
    "GlobalIPv6PrefixLen": 0,
    "MacAddress": "02:42:ac:11:00:02",
    "DriverOpts": null
  }
}
```

As you can see, my gateway address is 172.17.0.1, so you will need to put in `gotify:DBPASS@tcp(172.17.0.1)/gotifydb?charset=utf8&parseTime=True&loc=Local` as the connection string.

**Comment by mskian** [comment]
I tried Now that error is gone but it's not to port 80 server

My configuration

```
# Example configuration file for the server.
# Save it to `config.yml` when edited

server:
  listenaddr: "" # the address to bind on, leave empty to bind on all addresses
  port: 80 # the port the HTTP server will listen on

  ssl:
    enabled: true # if https should be enabled
    redirecttohttps: true # redirect to https if site is accessed by http
    listenaddr: "" # the address to bind on, leave empty to bind on all addresses
    port: 443 # the https port
    certfile: # the cert file (leave empty when using letsencrypt)
    certkey: # the cert key (leave empty when using letsencrypt)
    letsencrypt:
      enabled: true # if the certificate should be requested from letsencrypt
      accepttos: true # if you accept the tos from letsencrypt
      cache: /var/gotify/data/certs # the directory of the cache from letsencrypt
      hosts: # the hosts for which letsencrypt should request certificates
      - push.example.com
  
  responseheaders: # response headers are added to every response (default: none)
    Access-Control-Allow-Origin: "*"
    Access-Control-Allow-Methods: "GET,POST"

  stream:
    allowedorigins: # allowed origins for websocket connections (same origin is always allowed)
      - ".+.example.com"
      - "push.example.com"

database: # for database see (configure database section)
  dialect: mysql
  connection: gotify:DBPASS#@tcp(172.17.0.1)/gotifydb?charset=utf8&parseTime=True&loc=Local

defaultuser: # on database creation, gotify creates an admin user
  name: admin # the username of the default user
  pass: admin # the password of the default user
passstrength: 10 # the bcrypt password strength (higher = better but also slower)
uploadedimagesdir: /var/gotify/data/images # the directory for storing uploaded images
pluginsdir: /var/gotify/data/plugins # the directory where plugin resides
```
```
