### ISSUE TITLE
Plugin Configuration is stored as varbinary(255) on mariaDB

### ISSUE THREAD

**Issue by eternal-flame-AD** [gotify/server#195]
**Can the issue be reproduced with the latest available release? (y/n)**
Yes
**Which one is the environment gotify server is running in?**
- [ ] Docker
- [X] Linux machine
- [ ] Windows machine
<details><summary>Docker startup command or config file here (please mask sensitive information)</summary><br>

```
server:
  listenaddr: "127.0.0.1"
  port: 10000 # the port for the http server
  ssl:
    enabled: false # if https should be enabled
    redirecttohttps: true # redirect to https if site is accessed by http
    port: 443 # the https port
    certfile: # the cert file (leave empty when using letsencrypt)
    certkey: # the cert key (leave empty when using letsencrypt)
    letsencrypt:
      enabled: false # if the certificate should be requested from letsencrypt
      accepttos: false # if you accept the tos from letsencrypt
      cache: data/certs # the directory of the cache from letsencrypt
      hosts: # the hosts for which letsencrypt should request certificates
      - mydomain.tld
      - myotherdomain.tld
  responseheaders: # response headers are added to every response (default: none)
  stream:
    allowedorigins: # allowed origins for websocket connections (same origin is always allowed)
      - ".+.example.com"
      - "otherdomain.com"
database: # for database see (configure database section)
  dialect: mysql
  connection: root:root@/gotify?charset=utf8&parseTime=True&loc=Local
defaultuser: # on database creation, gotify creates an admin user
  name: admin # the username of the default user
  pass: admin # the password of the default user
passstrength: 10 # the bcrypt password strength (higher = better but also slower)
uploadedimagesdir: data/images # the directory for storing uploaded images
pluginsdir: data/plugins
```
</details>

**Do you have an reverse proxy installed in front of gotify server? (Please select None if the problem can be reproduced without the presense of a reverse proxy)**
- [X] None
- [ ] Nginx
- [ ] Apache
- [ ] Caddy
<details><summary>Reverse proxy configuration (please mask sensitive information)</summary><br>

```

```
</details>

**On which client do you experience problems? (Select as many as you can see)**
- [X] WebUI
- [X] gotify-cli
- [X] Android Client 
- [X] 3rd-party API call (Please include your code)

**What did you do?**

Ran a plugin with configuration storage.

**What did you expect to see?**

Configuration is stored correctly.

**What did you see instead? (Include screenshots, android logcat/request dumps if possible)**

A database error occured
```
(Error 1406: Data too long for column 'config' at row 1) 
[2019-06-08 12:04:21]  
panic: Error 1406: Data too long for column 'config' at row 1
```

The `plugin_confs` table is initialized with the column `config` of type `varbinary(255)`, which is too small.
```
MariaDB [gotify]> describe plugin_confs;
+----------------+------------------+------+-----+---------+----------------+
| Field          | Type             | Null | Key | Default | Extra          |
+----------------+------------------+------+-----+---------+----------------+
| id             | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| user_id        | int(10) unsigned | YES  |     | NULL    |                |
| module_path    | text             | YES  |     | NULL    |                |
| token          | varchar(180)     | YES  | UNI | NULL    |                |
| application_id | int(10) unsigned | YES  |     | NULL    |                |
| enabled        | tinyint(1)       | YES  |     | NULL    |                |
| config         | varbinary(255)   | YES  |     | NULL    |                |
| storage        | varbinary(255)   | YES  |     | NULL    |                |
+----------------+------------------+------+-----+---------+----------------+
8 rows in set (0.000 sec)
```
