### ISSUE TITLE
Status Code 0 trying to config SSL

### ISSUE THREAD

**Issue by jfmoura** [gotify/server#201]
**Have you read the documentation?**
- [X] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [ ] Docker
- [X] Linux native platform
- [ ] Windows native platform

I'm having difficulties setting up the HTTPS access
I created a SSL certificates self signed on Ubuntu 18.04, configured and run gotify-linux-amd64 showing this:
Starting Gotify version 2.0.5@2019-04-14-14:11:45
Started Listeninf for TLS connection on :444
Started Listening for plain HTTP connection on :81

When I try to connect Gotify(Android client) with the string:
https://192.168.1.50:444

Showed me the next error:
Request to 'https://192.168.1.50:444/version' failed with status code 0

Additionally, I loaded the CA Certificate without problems and showed me the correct feedback information.
....
my config.yml file is...
```
server:
  listenaddr: "" # the address to bind on, leave empty to bind on all addresses
  port: 81 # the port the HTTP server will listen on

  ssl:
    enabled: true # if https should be enabled
    redirecttohttps: true # redirect to https if site is accessed by http
    listenaddr: "" # the address to bind on, leave empty to bind on all addresses
    port: 444 # 443 the https port
    certfile: /etc/ssl/private/server.crt # the cert file (leave empty when using letsencrypt)
    certkey:  /etc/ssl/private/server.key # the cert key (leave empty when using letsencrypt)
    letsencrypt:
      enabled: false # if the certificate should be requested from letsencrypt
      accepttos: false # if you accept the tos from letsencrypt
      cache: data/certs # the directory of the cache from letsencrypt
      hosts: # the hosts for which letsencrypt should request certificates
      - mydomain.tld
      - myotherdomain.tld
  
  responseheaders: # response headers are added to every response (default: none)
    Access-Control-Allow-Origin: "*"
    Access-Control-Allow-Methods: "GET,POST"

  stream:
    allowedorigins: # allowed origins for websocket connections (same origin is always allowed)
      - ".+.example.com"
      - "otherdomain.com"

database: # for database see (configure database section)
  dialect: sqlite3
  connection: data/gotify.db

defaultuser: # on database creation, gotify creates an admin user
  name: admin # the username of the default user
  pass: admin # the password of the default user
passstrength: 10 # the bcrypt password strength (higher = better but also slower)
uploadedimagesdir: data/images # the directory for storing uploaded images
pluginsdir: data/plugins # the directory where plugin resides
```

Thank you in advanced
