### ISSUE TITLE
Gotify Server behind HAProxy?

### ISSUE THREAD

**Issue by superwinni2** [gotify/server#213]
Anyone with a Server behind HAProxy?

I always got Timeouts after ~1 Minute... 
Already tried difference timeouts but nothing helps...

Thanks

**Comment by patrick-othmer** [comment]
Here :)
Haproxy 1.8.8 with mode http. Working without a problem.

**Comment by superwinni2** [comment]
> Here :)
> Haproxy 1.8.8 with mode http. Working without a problem.

The big problem as far as I know is, that Gotify uses a Websocket connection. Due to that, HAProxy can't handle it as good as "normal" http connections....

**Comment by patrick-othmer** [comment]
Haproxy detects websocket request and switch automatical
 
https://www.haproxy.com/de/blog/websockets-load-balancing-with-haproxy/

Wed Sep 25 12:48:40 GMT+02:00 2019 superwinni2 <notifications@github.com>:

**Comment by superwinni2** [comment]
Okay Thanks :)
In a few days I will give it a try :)

**Comment by superwinni2** [comment]
After many many tries and failures I can't get it done....
I'm lost :(
Maybe somebody can help please?

My config at the moment:
```
root@OPNsense1:~ # cat /usr/local/etc/haproxy.conf
#
# Automatically generated configuration.
# Do not edit this file manually.
#

global
    # NOTE: Could be a security issue, but required for some feature.
    uid                         80
    gid                         80
    chroot                      /var/haproxy
    daemon
    stats                       socket /var/run/haproxy.socket level admin
    nbproc                      1
    nbthread                    1
    tune.ssl.default-dh-param   1024
    spread-checks               0
    tune.chksize                16384
    tune.bufsize                16384
    tune.lua.maxmem             0
    log /var/run/log local0

defaults
    log     global
    option redispatch -1
    timeout client 30s
    timeout connect 30s
    timeout server 30s
    retries 3

# autogenerated entries for ACLs

# autogenerated entries for config in backends/frontends

# autogenerated entries for stats


# Frontend: WAN_https ()
frontend WAN_https
    http-response set-header Strict-Transport-Security "max-age=15768000"
    bind 192.168.178.4:443 name 192.168.178.4:443 ssl no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets ciphers ECDHE-RSA-AES256-GCM-SHA384 crt-list /tmp/haproxy/ssl/5c852b4aef9e88.45675078.certlist
    bind 192.168.178.191:443 name 192.168.178.191:443 ssl no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets ciphers ECDHE-RSA-AES256-GCM-SHA384 crt-list /tmp/haproxy/ssl/5c852b4aef9e88.45675078.certlist
    mode http
    option http-server-close
    option forwardfor
    # tuning options
    timeout client 25s
    timeout http-request 15s
    timeout http-keep-alive 1s

    # logging options
    option dontlognull
    # ACL: Host_ist_nextc_domain_de
    acl acl_5d36cc72e11301.35692099 hdr(host) -i nextc.domain.de
    # ACL: Host_ist_push_domain_de
    acl acl_5cdf1ec3cfc2b4.19528643 hdr(host) -i push.domain.de
    # ACL: Host_ist_sara_domain_de
    acl acl_5c9565a43aac51.76259134 hdr(host) -i sara.domain.de
    # ACL: Pfad_beginnt_mit_acme_challenge
    acl acl_5ca7b6170c5440.28623250 path_beg -i /.well-known/acme-challenge/
    # ACL: hdr_connection_upgrade
    acl acl_5d8da5608188b5.74519793 hdr(Connection) -i upgrade
    # ACL: hdr_upgrade_websocket
    acl acl_5d8da63d2fb281.29027040 hdr(Upgrade) -i websocket

    # ACTION: SSL Redirect ungültig
    http-request redirect location http://google.de unless acl_5d36cc72e11301.35692099 || acl_5cdf1ec3cfc2b4.19528643 || acl_5c9565a43aac51.76259134

    # ACTION: redirect_acme_challenges
    use_backend acme_challenge_backend if acl_5ca7b6170c5440.28623250
    # ACTION: Rule_backend_gotify
    use_backend BackendPool_Gotify if acl_5cdf1ec3cfc2b4.19528643
    # ACTION: test test
    use_backend BackendPool_Gotify if acl_5d8da5608188b5.74519793 acl_5d8da63d2fb281.29027040
    # ACTION: Rule_backend_nextc
    use_backend BackendPool_Nextcloud if acl_5d36cc72e11301.35692099

# Frontend: WAN_http ()
frontend WAN_http
    bind 192.168.178.191:80 name 192.168.178.191:80
    bind 192.168.178.4:80 name 192.168.178.4:80
    mode http
    option http-keep-alive
    # tuning options
    timeout client 30s

    # logging options
    # ACL: Connection_is_http
    acl acl_5ca7acc8d98007.18433528 ssl_fc

    # ACTION: https redirect
    http-request redirect scheme https code 301 if !acl_5ca7acc8d98007.18433528


# Backend: BackendPool_Sara ()
backend BackendPool_Sara
    # health checking is DISABLED
    mode http
    balance source

    # tuning options
    timeout connect 1m
    timeout server 30s
    http-reuse never
    server realSara 10.10.20.101:80

# Backend: acme_challenge_backend (Added by Let's Encrypt plugin)
backend acme_challenge_backend
    # health checking is DISABLED
    mode http
    balance source
    # stickiness
    stick-table type ip size 50k expire 30m
    stick on src
    # tuning options
    timeout connect 30s
    timeout server 30s
    http-reuse never
    server acme_challenge_host 127.0.0.1:43580

# Backend: BackendPool_Gotify ()
backend BackendPool_Gotify
    # health checking is DISABLED
    mode http
    balance source
    # stickiness
    stick-table type ip size 50k expire 30m
    cookie SRVCOOKIE prefix
    # tuning options
    timeout connect 30s
    timeout server 30s
    server gotify 10.10.20.110:8080 cookie 5cdf1cfe57734448938021

# Backend: BackendPool_Nextcloud ()
backend BackendPool_Nextcloud
    # health checking is DISABLED
    mode http
    balance source
    # stickiness
    stick-table type ip size 50k expire 30m
    stick on src
    # tuning options
    timeout connect 2m
    timeout server 2m
    http-reuse never
    server nextcloud 10.10.20.103:443 ssl verify none
```

**Comment by profy12** [comment]
Nothink to configure with haproxy 1.8 to use websocket but use theses settings for socket timeout :
```
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    timeout tunnel        3600s
```

**Comment by jmattheis** [comment]
If you have a working config feel free to add it to https://github.com/gotify/website (:.

**Comment by superwinni2** [comment]
Mhmm.... 
I tried it now without HAproxy... Even the same error. Always some connection resets... every few secunds to a minute...
I've did a port forwarding with port 12345
Is there anything else where I can check anything?

Config.yml:
```
# Example configuration file for the server.
# Save it to `config.yml` when edited

server:
  listenaddr: "" # the address to bind on, leave empty to bind on all addresses
  port: 8080 # the port the HTTP server will listen on

  ssl:
    enabled: false # if https should be enabled
    redirecttohttps: false # redirect to https if site is accessed by http
    listenaddr: "" # the address to bind on, leave empty to bind on all addresses
    port: 443 # the https port
    certfile: # the cert file (leave empty when using letsencrypt)
    certkey: # the cert key (leave empty when using letsencrypt)
    letsencrypt:
      enabled: false # if the certificate should be requested from letsencrypt
      accepttos: false # if you accept the tos from letsencrypt
      cache: data/certs # the directory of the cache from letsencrypt
      hosts: # the hosts for which letsencrypt should request certificates
      - mydomain.tld
      - myotherdomain.tld

  responseheaders: # response headers are added to every response (default: none)
    Access-Control-Allow-Origin: "*"
    Access-Control-Allow-Methods: "GET,POST"

  stream:
    allowedorigins: # allowed origins for websocket connections (same origin is always allowed)
      - ".+.example.com"
      - "otherdomain.com"
      - "mydomain.de"
      - ".+.mydomain.de"
      - "gotify.mydomain.de"
#
#      - ".+.patwin.de"
#      - "*"

database: # for database see (configure database section)
  dialect: mysql
  connection: gotify:secret@/gotifydb?charset=utf8&parseTime=True&loc=Local

defaultuser: # on database creation, gotify creates an admin user
  name: admin # the username of the default user
  pass: password # the password of the default user
passstrength: 10 # the bcrypt password strength (higher = better but also slower)
uploadedimagesdir: data/images # the directory for storing uploaded images
pluginsdir: data/plugins # the directory where plugin resides

```

Log of Android Phone:
![Screenshot_2019-09-30-11-37-35](https://user-images.githubusercontent.com/42318077/65867480-cad34400-e376-11e9-8aae-d83d22ee2543.png)
