### ISSUE TITLE
Systemd Installer Script

### ISSUE THREAD

**Issue by fkellner** [gotify/server#238]
**Problem:**
In order to run gotify as a service using `systemd` (present e.g. on Amazon Linux or Debian-based Linux-Distributions like Ubuntu) I had to write my own `gotify.service` file, create a user, copy the files to the right locations, edit the config...
**Feature**
Since this is a standard solution, it would be nice to include the .service and edited `config.yml` as well as an install- and uninstall-script in official distribution for linux.
I have already written such a script that I tested successfully on an Ubuntu Server 18.04 instance that I am running in (very small-scale) production. Logging to file works semi-reliably (plus Ubuntu does not yet have a version of systemd that supports appending to files (>=240 needed)), but there is always `journalctl -u gotify` to access logs.

If someone double-checks my files and tells me where to put them so they are included in the zip file, I would be happy to create a pull request ;)

(In the following the contents of the files, but they are also attached: [gotify-systemd-installation.zip](https://github.com/gotify/server/files/3823337/gotify-systemd-installation.zip))

`gotify.service`: 
```
[Unit]
Description=gotify

[Service]
Type=simple
User=gotify
ExecStart=/usr/share/gotify/bin/gotify-linux-amd64
Restart=always
# WorkingDirectory=/usr/share/gotify
# these files are of limited use since they are overwritten each time the service restarts
# append is supported since systemd version 240, 'systemctl --version' currently yields 237 on Ubuntu Server 18.04
# for full logs, see 'journalctl -u gotify'
StandardOutput=file:/var/log/gotify/gotify.log
StandardError=file:/var/log/gotify/gotify-error.log

[Install]
WantedBy=multi-user.target
```

`systemd-config.yml`
```yml
# Example configuration file for the server.
# Save it to `config.yml` when edited

server:
  listenaddr: "" # the address to bind on, leave empty to bind on all addresses
  port: 8080 # the port the HTTP server will listen on. 8080 instead of 80 since we do not run as root

  ssl:
    enabled: false # if https should be enabled
    redirecttohttps: false # redirect to https if site is accessed by http
    listenaddr: "" # the address to bind on, leave empty to bind on all addresses
    port: 443 # the https port
    certfile: # the cert file (leave empty when using letsencrypt)
    certkey: # the cert key (leave empty when using letsencrypt)
    letsencrypt:
      enabled: false # if the certificate should be requested from letsencrypt
      accepttos: false # if you accept the tos from letsencrypt
      cache: data/certs # the directory of the cache from letsencrypt
      hosts: # the hosts for which letsencrypt should request certificates
#      - mydomain.tld
#      - myotherdomain.tld

  responseheaders: # response headers are added to every response (default: none)
    Access-Control-Allow-Origin: "*"
    Access-Control-Allow-Methods: "GET,POST"

  stream:
    allowedorigins: # allowed origins for websocket connections (same origin is always allowed)
#      - "" # activate this for accessing from an electron app
#      - "otherdomain.com"

database: # for database see (configure database section)
  dialect: sqlite3
  connection: /var/lib/gotify/gotify.db

defaultuser: # on database creation, gotify creates an admin user
  name: admin # the username of the default user
  pass: admin # the password of the default user
passstrength: 10 # the bcrypt password strength (higher = better but also slower)
uploadedimagesdir: /var/lib/gotify/images # the directory for storing uploaded images
pluginsdir: /var/lib/gotify/plugins # the directory where plugin resides
```

`install-gotify-systemd.sh`
```bash
#!/bin/bash
sudo systemctl stop gotify.service
sudo rm -rf /etc/systemd/system/gotify.service
sudo useradd -r gotify
sudo cp gotify.service /etc/systemd/system
sudo mkdir -p /usr/share/gotify/bin && sudo cp gotify-linux-amd64 /usr/share/gotify/bin
sudo mkdir /etc/gotify && sudo cp systemd-config.yml /etc/gotify/config.yml
sudo mkdir /var/log/gotify
sudo mkdir -p /var/lib/gotify/images && sudo mkdir /var/lib/gotify/plugins && sudo chown -R gotify /var/lib/gotify
sudo systemctl daemon-reload
echo "Service gotify installed"
echo "- Binary is in /usr/share/gotify/bin"
echo "- Sqlite database is in /var/lib/gotify"
echo "- config is in /etc/gotify"
echo "- Access logs via journalctl -u gotify or at /var/log/gotify"
echo "- Start with sudo systemctl start gotify"
echo "- Start at boot with sudo systemctl enable gotify"
```

`uninstall-gotify-systemd.sh`
```bash
#!/bin/bash
sudo systemctl stop gotify.service
sudo rm -rf /etc/systemd/system/gotify.service && echo "removed .service file"
sudo rm -rf /etc/gotify && echo "removed config dir"
sudo rm -rf /usr/share/gotify && echo "removed binaries"
sudo rm -rf /var/log/gotify && echo "removed logs"
sudo rm -rf /var/lib/gotify && echo "removed data"
sudo userdel -f gotify && echo "user gotify deleted"
sudo systemctl daemon-reload && echo "uninstall complete"
```
