### ISSUE TITLE
ACMEv1 deprecation response from letsencrypt

### ISSUE THREAD

**Issue by prg318** [gotify/server#243]
**Have you read the documentation?**
- [X] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [ ] Docker
- [X] Linux native platform
- [ ] Windows native platform

**Describe your problem**
I'm having difficulties setting up gotify-server to use letsecnrypt to request a certificate.  I receive the following error message when I start gotify with letsencrypt enabled:

```
Nov 27 19:42:30 fibre gotify-server[263471]: http: TLS handshake error from 98.110.116.172:53936: 403 urn:acme:error:unauthorized: Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.
```

....
my config is ...

```
# Example configuration file for the server.
# Save it to `config.yml` when edited

server:
  listenaddr: "" # the address to bind on, leave empty to bind on all addresses
  port: 6680 # the port the HTTP server will listen on

  ssl:
    enabled: true # if https should be enabled
    redirecttohttps: true # redirect to https if site is accessed by http
    listenaddr: "" # the address to bind on, leave empty to bind on all addresses
    port: 6443 # the https port
    certfile: /etc/gotify/cert.pem # the cert file (leave empty when using letsencrypt)
    certkey: /etc/gotify/privkey.pem # the cert key (leave empty when using letsencrypt)
    #certfile: /etc/letsencrypt/live/cert.pem # the cert file (leave empty when using letsencrypt)
    #certkey: /etc/letsencrypt/live/privkey.pem # the cert key (leave empty when using letsencrypt)
    letsencrypt:
      enabled: true # if the certificate should be requested from letsencrypt
      accepttos: true # if you accept the tos from letsencrypt
      cache: /var/lib/gotify/certs # the directory of the cache from letsencrypt
      hosts: # the hosts for which letsencrypt should request certificates
       - notify.mydomain.com
#      - mydomain.tld
#      - myotherdomain.tld

  responseheaders: # response headers are added to every response (default: none)
#    Access-Control-Allow-Origin: "*"
#    Access-Control-Allow-Methods: "GET,POST"

  stream:
    allowedorigins: # allowed origins for websocket connections (same origin is always allowed)
#      - ".+.example.com"
#      - "otherdomain.com"

database: # for database see (configure database section)
  dialect: sqlite3
  connection: /var/lib/gotify/gotify.db

defaultuser: # on database creation, gotify creates an admin user
  name: redacted # the username of the default user
  pass:redacted # the password of the default user
passstrength: 10 # the bcrypt password strength (higher = better but also slower)
uploadedimagesdir: /var/lib/gotify/images # the directory for storing uploaded images
pluginsdir: /var/lib/gotify/plugins # the directory where plugin resides
```

Thank you!  Wasn't sure if I was missing something or if this serves as an updated acme feature request
