### ISSUE TITLE
Expose the default port 80 in the Docker images

### ISSUE THREAD

**Issue by twelho** [gotify/server#251]
**Can the issue be reproduced with the latest available release? (y/n)**
Yes, with the latest Docker image (x86_64 tested, but I see the same issue in the armv7 image as well).

**Which one is the environment gotify server is running in?**
- [x] Docker
- [ ] Linux machine
- [ ] Windows machine
<details><summary>Docker startup command or config file here (please mask sensitive information)</summary><br>

```
version: '3.7'

services:
  gotify:
    container_name: gotify
    image: gotify/server
    restart: unless-stopped
    init: true
    volumes:
      - gotify_data:/app/data
    environment:
      - VIRTUAL_HOST=gotify.example.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=gotify.example.com
    networks:
      - proxy_net

volumes:
  gotify_data:
```
</details>

**Do you have an reverse proxy installed in front of gotify server? (Please select None if the problem can be reproduced without the presense of a reverse proxy)**
- [ ] None
- [x] Nginx
- [ ] Apache
- [ ] Caddy
<details><summary>Reverse proxy configuration (please mask sensitive information)</summary><br>

```
version: '3.7'

services:
  nginx_proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy:alpine
    restart: unless-stopped
    init: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - proxy_certs:/etc/nginx/certs:ro
      - proxy_vhostd:/etc/nginx/vhost.d:ro
      - proxy_html:/usr/share/nginx/html:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy_net

  letsencrypt_nginx_proxy_companion:
    container_name: letsencrypt-nginx-proxy-companion
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: unless-stopped
    init: true
    volumes:
      - proxy_certs:/etc/nginx/certs
      - proxy_vhostd:/etc/nginx/vhost.d
      - proxy_html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      
volumes:
  proxy_certs:
  proxy_vhostd:
  proxy_html:

networks:
  proxy_net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: proxy-net
```
</details>

**On which client do you experience problems? (Select as many as you can see)**
- [x] WebUI
- [ ] gotify-cli
- [ ] Android Client 
- [ ] 3rd-party API call (Please include your code)

**What did you do?**
I'm attempting to run the gotify server through the [jwilder/nginx-proxy](https://github.com/jwilder/nginx-proxy) reverse proxy with Let's Encrypt provided via [jrcs/letsencrypt-nginx-proxy-companion](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion) using `docker-compose`.

**What did you expect to see?**
The gotify Web UI to be accessible and SSL-secured via the proxy.

**What did you see instead? (Include screenshots, android logcat/request dumps if possible)**
Error 502 from the proxy due to the gotify server Docker image not exposing any ports. If I manually make the following Docker image the server becomes accessible without issues:
```
FROM gotify/server

# Expose the default port 80
EXPOSE 80
```

Would it be possible to add the `EXPOSE` directive to the gotify server Dockerfile? I have 10+ other containers running via the same proxy without issues, as they all `EXPOSE` by default. I can do a small PR that adds the line.

(There's also a cleaner way to add the `ca-certificates` package in the Dockerfiles, I can improve that as well in the PR if wanted.)

**Comment by jmattheis** [comment]
Hey @twelho,

feel free to file a PR. Improvements are always welcome.

As a side note: It is possible to specify the expose ports in the docker-compose file, tho having it declared inside the Dockerfile is the cleaner way.
```yaml
version: '3'

services:
  gotify:
    image: gotify/server
    volumes:
      - "./gotify_data:/app/data"
    expose:
      - "80"
```
