### ISSUE TITLE
Apps and Devices Getting Deleted

### ISSUE THREAD

**Issue by YouveGotMeowxy** [gotify/server#282]
**Can the issue be reproduced with the latest available release? (y/n)**

I Can't manually trigger the issue for some reason. I tried adding a dummy app, then restarting the container, but the app was still there (this time).

**Which one is the environment gotify server is running in?**
- [X] Docker
- [ ] Linux machine
- [ ] Windows machine
<details><summary>Docker startup command or config file here (please mask sensitive information)</summary><br>

```

version: '2'

services:

    gotify:
        container_name: gotify
        hostname: gotify
        image: gotify/server:latest
        environment:
            - GOTIFY_DATABASE_DIALECT=sqlite3
            - GOTIFY_DATABASE_CONNECTION=gotify.db
            - GOTIFY_DEFAULTUSER_NAME=redacted
            - GOTIFY_DEFAULTUSER_PASS=redacted
            - GOTIFY_PASSSTRENGTH=10
            - GOTIFY_UPLOADEDIMAGESDIR=images
            - GOTIFY_PLUGINSDIR=plugins
        restart: unless-stopped
        volumes:
            - 'my_gotify_data:/app/data gotify/server'
        networks:
            - mm

volumes:
   me_gotify_data:
     external: true

networks:
  mm:
    external:
      name: my-misc

```
</details>

**Do you have an reverse proxy installed in front of gotify server? (Please select None if the problem can be reproduced without the presense of a reverse proxy)**
- [ ] None
- [X] Nginx
- [ ] Apache
- [ ] Caddy
<details><summary>Reverse proxy configuration (please mask sensitive information)</summary><br>

```

```
</details>

**On which client do you experience problems? (Select as many as you can see)**
- [X] WebUI
- [ ] gotify-cli
- [ ] Android Client 
- [ ] 3rd-party API call (Please include your code)

**What did you do?**

Twice now, I've added several apps and devices; took time to name them how I like them, etc. Then randomly when I would come back to the UI days or weeks later, it was all just gone.

**What did you expect to see?**

All the apps and devices I manually added to still be there.

**What did you see instead? (Include screenshots, android logcat/request dumps if possible)**

It was almost like a fresh install, with the exception that my login/user is still there, and the dark theme persists. everything else is gone.

Currently using version 2.0.14
