### ISSUE TITLE
How to connect to a MySQL db?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [gotify/server#283]
**Have you read the documentation?**
- [ ] Yes, but it does not include related information regarding my question.
- [x] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [x] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**

I am trying to start a new instance of gotify using mysql instead of sqlite, and can't get it to connect to the MySQL server that runs in another container, placed in the same docker network as this gotify container, and with the hostname 'mysql'.

Normally in docker you can just place 2 containers in the same docker network, and use the container's name, or it's hostname, and docker will do all the resolving for you; you just call 'mysql' in any other container's db settings. I can't seem to figure out how to do this with gotify's config?

I have tried:

```
- GOTIFY_DATABASE_DIALECT=mysql
- GOTIFY_DATABASE_CONNECTION='gotify:mypw@mysql:3306/gotifydb?charset=utf8&parseTime=True&loc=Local'
```

But I just get errors in the gotify log like:

> Starting Gotify version 2.0.14@2020-02-18-18:48:32

> panic: default addr for network 'mysql:3306' unknown

> goroutine 1 [running]:

> main.main()

>	/proj/app.go:47 +0x4ed

Using this instead:

```
- GOTIFY_DATABASE_CONNECTION='gotify:mypw@tcp(mysql):3306/gotifydb?charset=utf8&parseTime=True&loc=Local'
```

Gives this error:

> Starting Gotify version 2.0.14@2020-02-18-18:48:32

> panic: invalid DSN: did you forget to escape a param value?

> goroutine 1 [running]:

> main.main()
>	/proj/app.go:47 +0x4ed

And so on ....

**Any errors, logs, or other information that might help us identify your problem**

Ex: `docker-compose.yml`, `nginx.conf`, android logcat, browser requests, etc.

<details><summary>Name of the information here</summary><br><pre>

contents here

</pre></details>

**Comment by jmattheis** [comment]
You need to use `root:password@tcp(mysql:3306)/gotify?charset=utf8&parseTime=True&loc=Local` Ensure, that mysql is ready before starting gotify.
```
version: '2'
 
services:
    gotify:
        container_name: gotify
        hostname: gotify
        image: gotify/server:latest
        environment:
            - GOTIFY_DATABASE_DIALECT=mysql
            - GOTIFY_DATABASE_CONNECTION=root:password@tcp(mysql:3306)/gotify?charset=utf8&parseTime=True&loc=Local
        restart: unless-stopped
        volumes:
            - "./data:/app/data"
    mysql:
        image: mariadb:10.1.15
        ports:
            - 1337:3306
        environment:
            MYSQL_ROOT_PASSWORD: "password"
            MYSQL_USER: "root"
            MYSQL_DATABASE: "gotify"
            MYSQL_ROOT_HOST: "%"
```
