### ISSUE TITLE
config.yml unmarshal errors 

### ISSUE THREAD

**Issue by ykfq** [gotify/server#284]
**Can the issue be reproduced with the latest available release? (y/n)**

**Which one is the environment gotify server is running in?**
- [ ] Docker
- [ ] Linux machine
- [x] kubernetes

Gotify-server runs perfectly on docker but fails on k8s, the error is(I even build the docker image from latest source code):
```bash
2020-03-23T02:18:09.944791737Z Starting Gotify version unknown@unknown
2020-03-23T02:18:09.947095845Z panic: yaml: unmarshal errors:
2020-03-23T02:18:09.954024281Z   line 1: cannot unmarshal !!str `tcp://1...` into int
2020-03-23T02:18:09.954035294Z 
2020-03-23T02:18:09.954038352Z goroutine 1 [running]:
2020-03-23T02:18:09.954040973Z github.com/gotify/server/config.Get(0xc0000ac150)
2020-03-23T02:18:09.954043572Z 	/proj/config/config.go:60 +0x31a
2020-03-23T02:18:09.954047214Z main.main()
2020-03-23T02:18:09.95405047Z 	/proj/app.go:34 +0x23c
```

uses the same `config.yml` file:
```yaml
server:
  listenaddr: ""
  port: 80
  ssl:
    enabled: false
    redirecttohttps: true
    listenaddr: ""
    port: 443
    certfile:
    certkey:
    letsencrypt:
      enabled: true
      accepttos: true
      cache: data/certs
      hosts:
      - push.xwfintech.com
  responseheaders:
    Access-Control-Allow-Origin: "*"
    Access-Control-Allow-Methods: "GET,POST"
  stream:
    allowedorigins:
      - ".+.xwfintech.com"
      - "push.xwfintech.com"
database:
  dialect: mysql
  connection: "db_gotify:db_gotify@tcp(192.168.100.10)/db_gotify?charset=utf8&parseTime=True&loc=Local"
defaultuser:
  name: admin
  pass: admin
passstrength: 10
uploadedimagesdir: data/images
pluginsdir: data/plugins
```

**Comment by ykfq** [comment]
I changed to use environment variables, the error is still, envs:
```bash
    spec:
      containers:
      - env:
        - name: GOTIFY_SERVER_SSL_ENABLED
          value: "false"
        - name: GOTIFY_DATABASE_DIALECT
          value: mysql
        - name: GOTIFY_DATABASE_CONNECTION
          value: db_gotify:db_gotify@tcp(192.168.100.10)/db_gotify?charset=utf8&parseTime=True&loc=Local
        - name: GOTIFY_DEFAULTUSER_NAME
          value: admin
        - name: GOTIFY_DEFAULTUSER_PASS
          value: admin
```

**Comment by jmattheis** [comment]
Does it really use the same config?
```
 line 1: cannot unmarshal !!str `tcp://1...` into int
```
there is no tcp:// in your config.

**Comment by ykfq** [comment]
I'm not sure

**Comment by ykfq** [comment]
confirmed:  the same config file works with docker, but failed when using it to create a configmap:
```bash
kubectl create cm gotify-config --from-file config.yml
```
and using the follow deployment file:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    qcloud-app: gotify-server
  name: gotify-server
  namespace: glenjiang
spec:
  replicas: 1
  selector:
    matchLabels:
      qcloud-app: gotify-server
  template:
    metadata:
      labels:
        qcloud-app: gotify-server
    spec:
      containers:
      - image: gotify/server:2.0.16
        imagePullPolicy: Always
        name: gotify-server
        ports:
        - containerPort: 80
          name: http-80
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/gotify/config.yml
          name: config-volume
          subPath: config.yml
      hostname: gotify-server
      restartPolicy: Always
      volumes:
      - configMap:
          defaultMode: 420
          name: gotify-config
        name: config-volume
---
apiVersion: v1
kind: Service
metadata:
  labels:
    qcloud-app: gotify-server
  name: gotify-server
  namespace: glenjiang
spec:
  ports:
  - name: http-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    qcloud-app: gotify-server
  type: ClusterIP
```

**Comment by jmattheis** [comment]
Well, I'm not into kubernetes, but you can use environment variables to configure gotify/server.

Kubernetes probably does something stupid with the config.

**Comment by nadihagh** [comment]
@ykfq there is no problem with config, remove service are from yaml file and write it to a new file called e.g. gotify.svc.yaml. first run deployment after that run service, I mean create service after deployment is created in kubernetes, I don't know why but it'll work.

**Comment by alexgorbatchev** [comment]
I can confirm that delaying creating a service does make it work...

**Comment by alexgorbatchev** [comment]
I do think there's a problem actually... It sounds like spinning up new pods while service exists will always lead to this problem. Deleting the service immediately allows a pod to start as expected.

So in summary, gotify-server will not boot up in k8s environment if there's a service associated with deployment.

**Comment by alexgorbatchev** [comment]
3 hours later I'm not able to get Gotify server to start if a Service already exists. I'm assuming that the presence of Service modifies container in some way that causes Gotify configuration reader to fail. If the Service is created after container boots up, everything works as expected.

**Comment by gashton** [comment]
Apologies for reopening the closed issue, but I ran into the same issue, debugged the cause and found a better solution than delaying service creation.

**PROBLEM**
K8s passes in helpful environmental variables to the container, when a service exists it passes a number of variables including the following port variable.

`GOTIFY_SERVER_PORT=tcp://10.98.77.217:8080`

The port variable is prefixed with the name of the k8s service '**gotify-server**' (capitalised).

This causes an issue with configuration parsing as configor looks at 'GOTIFY' prefixed variable which includes the server port variable, which is this exact variable. It expects this variable to be an integer, so when it attempts to unmarshal it, it fatally fails. 

https://github.com/gotify/server/blob/4c58f4a7423c61de3d0f4d64aa282d5eaea3d10a/config/config.go#L66

**SOLUTION**

The solution is to prefix the service name with anything other than 'GOTIFY' to prevent this clash.

e.g.

name: **app-gotify-server**

```
apiVersion: v1
kind: Service
metadata:
  labels:
    qcloud-app: gotify-server
  name: app-gotify-server
  namespace: glenjiang
spec:
  ports:
  - name: http-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    qcloud-app: gotify-server
  type: ClusterIP
```
