### ISSUE TITLE
Applications missing from WebUI

### ISSUE THREAD

**Issue by stumpylog** [gotify/server#290]
**Can the issue be reproduced with the latest available release? (y/n)**

**Which one is the environment gotify server is running in?**
- [x] Docker
<details><summary>Docker startup command or config file here (please mask sensitive information)</summary><br>

```
version: "3.7"
networks:
  system-net:
    name: system-net
    external: true
  media-net:
    name: media-net
    external: true
services:
  gotify:
    image: gotify/server
    container_name: gotify
    networks:
      - system-net
      - media-net
    volumes:
      - /opt/gotify:/app/data
    ports:
      - 9080:80
    restart: unless-stopped
```
</details>

**Do you have an reverse proxy installed in front of gotify server? (Please select None if the problem can be reproduced without the presense of a reverse proxy)**
- [x] None

**On which client do you experience problems? (Select as many as you can see)**
- [x] WebUI

**What did you do?**
I created several applications, connected them and tested each.

**What did you expect to see?**
The applications I created in the WebUI.

**What did you see instead? (Include screenshots, android logcat/request dumps if possible)**
The applications created were missing from the WebUI next time I logged in.  However, they still exist in the `gotify.db`.  You can see the originals, where I uploaded logos, and the new ones I created later, after the old applications went missing

<details>

```
sqlite> SELECT * from applications;
1|AXTGul2M2f..uk5|1|radarr||0|bRxCpm.k2E2X0emV7aCMaUZ50.png
2|AhzENRmXsdR42x6|1|sonarr||0|buWudKUmcdj.IMasN-ORBY-Tz.png
3|AD2nApkSEVp5dTd|1|bazarr||0|9cwRXFwep0WCdWDFHRcFHVZ8e.png
4|AATxhGK9Ham3alp|1|loki ouroboros||0|XwBA1EA7rOfca-x62ab3_DFZ3.png
5|AQ8S.ZFHg7chu8B|1|Tautulli||0|BaRWRk3X4NCwek53aaDigrt19.png
6|AIW4a_nAO.LQzrM|1|pi.hole ouroboros||0|
7|ApkmVlgSHyQ6hfC|2|ouroboros||0|
8|AHUAlL_vgoPg2Eq|2|sonarr||0|
9|AkACzr3AQ3A_olk|2|radarr||0|
sqlite>
```
</details>
