### ISSUE TITLE
[Docker] Run application with a non-root user

### ISSUE THREAD

**Issue by x-jokay** [gotify/server#306]
**Is your feature request related to a problem? Please describe.**
Kind of.

**Describe the solution you'd like**
Run application with a non-root user.

**Describe alternatives you've considered**
Running it as it is.

**Additional context**
* [docs.docker.com](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user)
* [running a container with a non-root user](https://medium.com/better-programming/running-a-container-with-a-non-root-user-e35830d1f42a)

**Comment by jmattheis** [comment]
Related #187

**Comment by jmattheis** [comment]
You can run gotify as non root user by defining the user with `--user`. Changing the user inside the container will break all users, thus, requires manual intervention. I don't think it is worth making a breaking change, for something that can be archived by configuration.

Example.
```bash
jm@dyne ~/src/playground/gotify λ mkdir data
jm@dyne ~/src/playground/gotify λ docker run --name goti \
                 -d --rm --user $UID:$GID \
                 -e GOTIFY_SERVER_PORT=8080 \
                 -v $PWD/data:/app/data gotify/server:2.0.15
3081a39980b242a11f06e9606aa4d7f501ebd317749a64ccac6de94e3a80a171
jm@dyne ~/src/playground/gotify λ docker exec goti ps aux
PID   USER     TIME  COMMAND
    1 1000      0:00 ./gotify-app
   11 1000      0:00 ps aux
jm@dyne ~/src/playground/gotify λ ll
total 4.0K
drwxr-xr-x 4 jm jm 4.0K Apr 27 19:21 data
jm@dyne ~/src/playground/gotify λ ll data/
total 84K
-rw-r--r-- 1 jm jm  72K Apr 27 19:21 gotify.db
drwxr-xr-x 2 jm jm 4.0K Apr 27 19:21 images
drwxr-xr-x 2 jm jm 4.0K Apr 27 19:21 plugins
```

**Comment by x-jokay** [comment]
Sorry, didn't see #187.

I don't think using the param `--user` is a good idea as the majority may use the container image without this param.

It should be secure by default not by requiring a param.

Yes, it's a breaking change, but for the good :wink:

**Comment by jmattheis** [comment]
I also think it is a good idea to have secure defaults but as a user of software it sucks if it breaks. Let me think a little about this.

**Comment by pred2k** [comment]
i've added `user: 1000:1000` to my `compose.yaml` which ran as root **before**:

```yaml
services:
  gotify:
    image: gotify/server
    user: 1000:1000
    volumes:
      - './gotify_data:/app/data'
```
Then i run `chown -R 1000:1000 ./gotify_data/`.

and since now it's running as non-root without an issue
```
docker compose exec gotify id
uid=1000 gid=1000 groups=1000
```

**i think such a change is worth it to improve the container runtime security!**

i did it even harder:

```yaml
services:
  gotify:
    image: gotify/server
    container_name: gotify
    user: 1000:1000
    read_only: true
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    volumes:
      - './gotify_data:/app/data'
    environment:
      GOTIFY_SERVER_PORT: 8080
```
