### ISSUE TITLE
Cannot login after upgrade to 2.0.15

### ISSUE THREAD

**Issue by rerobins** [gotify/server#313]
**Can the issue be reproduced with the latest available release? (y/n)**
Yep

**Which one is the environment gotify server is running in?**
- [ ] Docker
- [x] Linux machine
- [ ] Windows machine
<details><summary>Docker startup command or config file here (please mask sensitive information)</summary><br>

```
server:
  listenaddr: "" # the address to bind on, leave empty to bind on all addresses
  port: 8123 # the port for the http server
  ssl:
    enabled: false # if https should be enabled
    redirecttohttps: true # redirect to https if site is accessed by http
    listenaddr: "" # the address to bind on, leave empty to bind on all addresses
    port: 443 # the https port
    certfile: # the cert file (leave empty when using letsencrypt)
    certkey: # the cert key (leave empty when using letsencrypt)
    letsencrypt:
      enabled: false # if the certificate should be requested from letsencrypt
      accepttos: false # if you accept the tos from letsencrypt
      cache: data/certs # the directory of the cache from letsencrypt
      hosts: # the hosts for which letsencrypt should request certificates
        - mydomain.tld
        - myotherdomain.tld
  responseheaders: # response headers are added to every response (default: none)
    Access-Control-Allow-Origin: "*"
    Access-Control-Allow-Methods: "GET,POST"
  stream:
    allowedorigins: # allowed origins for websocket connections (same origin is always allowed, default only same origin)
      - ".+.example.com"
      - "otherdomain.com"
database: # see below
  dialect: sqlite3
  connection: /usr/local/data/home/gotify/gotify.db
defaultuser: # on database creation, gotify creates an admin user (these values will only be used for the first start, if you want to edit the user after the first start use the WebUI)
  name: admin # the username of the default user
  pass: admin # the password of the default user
passstrength: 10 # the bcrypt password strength (higher = better but also slower)
uploadedimagesdir: /usr/local/data/home/gotify/data/images # the directory for storing uploaded images
pluginsdir: /usr/local/data/home/gotify/data/plugins # the directory where plugin resides (leave empty to disable plugins)

```
</details>

**Do you have an reverse proxy installed in front of gotify server? (Please select None if the problem can be reproduced without the presense of a reverse proxy)**
- [ ] None
- [x] Nginx
- [ ] Apache
- [ ] Caddy
<details><summary>Reverse proxy configuration (please mask sensitive information)</summary><br>

```
server {

  # Here goes your domain / subdomain
  server_name push.hostname.lan

  location / {
    # We set up the reverse proxy
    proxy_pass         http://127.0.0.1:8123/
    proxy_http_version 1.1;

    # Ensuring it can use websockets
    proxy_set_header   Upgrade $http_upgrade;
    proxy_set_header   Connection "upgrade";
    proxy_set_header   X-Real-IP $remote_addr;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Proto http;
    proxy_redirect     http:// $scheme://;

    # These sets the timeout so that the websocket can stay alive
    proxy_connect_timeout   7m;
    proxy_send_timeout      7m;
    proxy_read_timeout      7m;
  }
}

```
</details>

**On which client do you experience problems? (Select as many as you can see)**
- [x] WebUI
- [ ] gotify-cli
- [ ] Android Client 
- [ ] 3rd-party API call (Please include your code)

**What did you do?**

Upgraded from 2.0.14 to 2.0.15.  Attempted to login, Login failed.  Went back to 2.0.14 and am able to login again.  Android application works with updated server, but webui does not.

**What did you do?**

Upgraded from 2.0.14 to 2.0.15.  Attempted to login, Login failed.  Went back to 2.0.14 and am able to login again.  Android application works with updated server, but webui does not.

**What did you expect to see?**

Log in to 2.0.15.

**What did you see instead? (Include screenshots, android logcat/request dumps if possible)**

Login Failed.

Additional Notes:

* ARM 7 release 2.0.15
* Debian 10.3
