### ISSUE TITLE
"Login failed" when trying to connect to ui with default login/pass

### ISSUE THREAD

**Issue by ziobombo** [gotify/server#336]
**Can the issue be reproduced with the latest available release? (y/n)**
yes

**Which one is the environment gotify server is running in?**
- [X] Docker
- [ ] Linux machine
- [ ] Windows machine
<details><summary>Docker startup command or config file here (please mask sensitive information)</summary><br>
My docker-compose.yml

```
version: "3.6"

services:
  gotify:
    image: gotify/server
    container_name: gotify
    network_mode: host
    environment:
      - GOTIFY_SERVER_PORT=7070
    volumes:
      - /home/server0/configuration/Gotify:/app/data
</details>
```

**Do you have an reverse proxy installed in front of gotify server? (Please select None if the problem can be reproduced without the presense of a reverse proxy)**
- [X] None
- [ ] Nginx
- [ ] Apache
- [ ] Caddy

**On which client do you experience problems? (Select as many as you can see)**
- [X] WebUI
- [ ] gotify-cli
- [ ] Android Client 
- [ ] 3rd-party API call (Please include your code)

**What did you do?**

tried to login with admin/admin

**What did you expect to see?**

login succeeded

**What did you see instead? (Include screenshots, android logcat/request dumps if possible)**
a bottom left popup saying: "Login failed"
![image](https://user-images.githubusercontent.com/10390360/85847632-0ab14580-b7a8-11ea-9a7b-b40a9fd06137.png)
