### ISSUE TITLE
Gotify keeps hosing my uploaded images

### ISSUE THREAD

**Issue by STaRDoGG** [gotify/server#389]
**Can the issue be reproduced with the latest available release? (y/n)**
yes. this is currently version 2.0.21

**Which one is the environment gotify server is running in?**
- [x] Docker
- [ ] Linux machine
- [ ] Windows machine
<details><summary>Docker startup command or config file here (please mask sensitive information)</summary><br>

```
    gotify:
        hostname: gotify
        image: gotify/server:latest
        environment:
            - GOTIFY_DATABASE_DIALECT=mysql
            - GOTIFY_DATABASE_CONNECTION='gotify:redacted@tcp(mysql:3306)/gotify?charset=utf8&parseTime=True&loc=Local'
            - GOTIFY_DEFAULTUSER_NAME=redacted
            - GOTIFY_DEFAULTUSER_PASS='redacted'
            - GOTIFY_PASSSTRENGTH=10
        volumes:
            - gotify_data:/app/data gotify/server:rw
            - /opt/docker/configs/icons:/icons:rw
            - /etc/localtime:/etc/localtime:ro
        deploy:
            mode: replicated
            replicas: 1
            placement:
              constraints:
                - node.labels.MainDaemon == true
            restart_policy:
              condition: any
        networks:
            - om
            - odb
```
</details>

**Do you have an reverse proxy installed in front of gotify server? (Please select None if the problem can be reproduced without the presense of a reverse proxy)**
- [ ] None
- [x] Nginx
- [ ] Apache
- [ ] Caddy
<details><summary>Reverse proxy configuration (please mask sensitive information)</summary><br>

```
n/a
```
</details>

**On which client do you experience problems? (Select as many as you can see)**
- [x] WebUI
- [ ] gotify-cli
- [ ] Android Client 
- [ ] 3rd-party API call (Please include your code)

**What did you do?**

I upload my icons in the Apps tab via clicking the cloud icon; they show properly for awhile after that, then randomly later on they just end up giving the broken image, like the screenshot below.

I have my gotify data folder setup already, so I would *think* the changes would persist, but they dont.

**What did you expect to see?**

The icons I setup to persist.

**What did you see instead? (Include screenshots, android logcat/request dumps if possible)**

The icons I setup do not persist.

![image](https://user-images.githubusercontent.com/1524526/107718731-3849f100-6c9c-11eb-86e4-ffe7608b1f36.png)
