### ISSUE TITLE
Secrets?

### ISSUE THREAD

**Issue by STaRDoGG** [gotify/server#392]
Does Gotify support docker secrets? In particular for the `GOTIFY_DEFAULTUSER_PASS` variable? I've looked at the docs but see no  reference. if  not, can it be added?

**Comment by jmattheis** [comment]
No this is probably not supported currently, but you can easily change the password after the container is started.

**Comment by STaRDoGG** [comment]
Here's an example of how to add it in, if you're interested: https://github.com/wallabag/docker/pull/248/files

**Comment by ColinHebert** [comment]
For now I'm using this hack:

```yaml
name: Notifications

services:
  gotify:
    image: gotify/server
    # Hack to get around the lack of secret support in Gotify
    entrypoint: ['/bin/sh', '-c', 'GOTIFY_DEFAULTUSER_PASS=$(cat /run/secrets/admin_password) ./gotify-app']
    secrets:
      - admin_password

secrets:
  admin_password:
    file: ./secrets/admin_password
```

It is not clean at all, but it works.

@jmattheis I reckon it could be a nice addition to configor; having a way to indicate that a configuration field can be either burnt in or specified through a filepath.
A flag on the parameter that allows the config file (or env variables) to specify `PREFIX_CATEGORY_FIELD-FILE=/blah` or
```yaml
category:
  field-file: /blah
```

If the `field-file` is specified, override the content of `field` with the content of the indicated file.
This way some variables (secret ones) can be filled in through the docker secret system (which uses files)
