### ISSUE TITLE
Trying to enable SSL via docker compose with environment variables

### ISSUE THREAD

**Issue by Brendonwbrown** [gotify/server#424]
I have read through documentation and relevant issues, and not found any solution related my specific issue.

I can successfully launch and use gotify container using docker compose (Portainer user).
I successfully use Nginx Proxy Manager to route internal and external http/https traffic to several FOSS applications in docker containers. I generally don't bother configuring certs for any since NPM has great Letsencrypt handling.

My successful compose file:
```
version: '3'
services:
  gotify:
    image: gotify/server:latest
    ports: 
      - 6081:80
      - 6444:443
    volumes:
    - /home/myuser/gotify/data:/app/data
    environment:
    - GOTIFY_SERVER_PORT=80
    restart: always
networks:
  default:
    external:
      name: appnet
```

When I add SSL environment variable 'GOTIFY_SERVER_SSL_ENABLED=true', however,  I end up with these logs on a loop and no Gotify.
```
Starting Gotify version 2.0.23@2021-06-19-10:08:25,
Started Listening for TLS connection on :443,
Started Listening for plain HTTP connection on :80,
2021/07/21 21:09:32 open : no such file or directory
```

(Failing) compose file with environment variables:
```
version: '3'
services:
  gotify:
    image: gotify/server:latest
    ports: 
      - 6081:80
      - 6444:443
    volumes:
    - /home/brendonwbrown/gotify/data:/app/data
    environment:
    - GOTIFY_SERVER_SSL_ENABLED=true
    - GOTIFY_SERVER_SSL_REDIRECTTOHTTPS=false
    - GOTIFY_SERVER_SSL_PORT=443
    - GOTIFY_SERVER_SSL_LETSENCRYPT_ENABLED=false
    restart: always
networks:
  default:
    external:
      name: ICMapps
```
I am starting to think that Gotify is failing because it's not finding any self-signed certs for SSL. I've noticed the environment variables `GOTIFY_SERVER_SSL_CERTFILE=` and `GOTIFY_SERVER_SSL_CERTKEY=`. Are there defaults I can provide the path to?
