### ISSUE TITLE
Error 401 when sending token through body or header key in lowercase

### ISSUE THREAD

**Issue by Salamafet** [gotify/server#429]
**Can the issue be reproduced with the latest available release? (y/n)**
Yes

**Which one is the environment gotify server is running in?**
- [x] Docker
- [ ] Linux machine
- [ ] Windows machine
<details><summary>Docker startup command or config file here (please mask sensitive information)</summary><br>

Docker compose file
``` yaml
version: "3"

services:
  gotify:
    image: gotify/server
    ports:
      - 8087:80
    environment:
      - GOTIFY_DEFAULTUSER_PASS=password
      - TZ=Europe/Paris
    volumes:
      - "./data:/app/data"
    labels:
      com.centurylinklabs.watchtower.enable: "true"
```
</details>

**Do you have an reverse proxy installed in front of gotify server? (Please select None if the problem can be reproduced without the presense of a reverse proxy)**
- [ ] None
- [ ] Apache
- [x] Nginx
- [ ] Caddy
<details><summary>Reverse proxy configuration (please mask sensitive information)</summary><br>

```
I use Nginx Proxy Manager
```
</details>

**On which client do you experience problems? (Select as many as you can see)**
- [ ] WebUI
- [ ] gotify-cli
- [ ] Android Client 
- [x] 3rd-party API call (Please include your code)

**What did you do?**

I try to send gotify message through the notification system of Synology. After many fails attempt, I have tested my request with Postman.

When I'm sending the following request with Postman:
``` json
{
  "token": "my-token",
  "title": "BlackBox",
  "priority": 5,
  "message": "Un nouvel événement système s'est produit sur votre BlackBox le 02/09/2021 à 10:36.\nMessage test de BlackBox"
}
```
I got the following error:
``` json
{
    "error": "Unauthorized",
    "errorCode": 401,
    "errorDescription": "you need to provide a valid access token or user credentials to access this api"
}
```

If I use the header key instead (X-Gotify-Key), it works.
