### ISSUE TITLE
unexpected EOF on websocket connection

### ISSUE THREAD

**Issue by mzch** [gotify/server#446]
**Have you read the documentation?**
- [x] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [ ] Docker
- [x] Linux native platform
- [ ] Windows native platform

**Describe your problem**

Websocket connection failed. Please see the following screenshot.

<img width="1494" alt="Screenhot" src="https://user-images.githubusercontent.com/621178/139694278-5e62d056-3bd2-4553-9c41-558e57d1246c.png">

Server OS: `Debian 11.1`
Reverse Proxy: `Apache 2.4.51`
Gotify Server: `2.1.0`
Client OS: `macOS 12.0.1`
Browser: `Chrome 95.0.4638.69`

**Any errors, logs, or other information that might help us identify your problem**

- Log
```
Nov  2 00:01:27 n07 gotify-linux-amd64[456]: [GIN] 2021/11/02 - 00:01:27 | 200 |    2.558142ms |  118.243.18.144 | GET      "/stream?token=[masked]"
Nov  2 00:01:32 n07 gotify-linux-amd64[456]: WebSocket: ReadError websocket: close 1006 (abnormal closure): unexpected EOF
Nov  2 00:01:33 n07 gotify-linux-amd64[456]: [GIN] 2021/11/02 - 00:01:33 | 200 |    3.119908ms |  118.243.18.144 | GET      "/current/user"
```
- config.yml
```
# Example configuration file for the server.
# Save it to `config.yml` when edited

server:
  keepaliveperiodseconds: 0 # 0 = use system default; set the interval in which keepalive packages will be sent. Only change this value if you know what you are doing.
  listenaddr: "127.0.0.1" # the address to bind on, leave empty to bind on all addresses
  port: 5000 # the port the HTTP server will listen on

  ssl:
    enabled: false # if https should be enabled
    redirecttohttps: true # redirect to https if site is accessed by http
    listenaddr: "" # the address to bind on, leave empty to bind on all addresses
    port: 443 # the https port
    certfile: # the cert file (leave empty when using letsencrypt)
    certkey: # the cert key (leave empty when using letsencrypt)
    letsencrypt:
      enabled: false # if the certificate should be requested from letsencrypt
      accepttos: false # if you accept the tos from letsencrypt
      cache: data/certs # the directory of the cache from letsencrypt
      hosts: # the hosts for which letsencrypt should request certificates
#      - mydomain.tld
#      - myotherdomain.tld

  responseheaders: # response headers are added to every response (default: none)
#    X-Custom-Header: "custom value"

  cors: # Sets cors headers only when needed and provides support for multiple allowed origins. Overrides Access-Control-* Headers in response headers.
    alloworigins:
#      - ".+.example.com"
#      - "otherdomain.com"
    allowmethods:
#      - "GET"
#      - "POST"
    allowheaders:
#      - "Authorization"
#      - "content-type"
  stream:
    pingperiodseconds: 45 # the interval in which websocket pings will be sent. Only change this value if you know what you are doing.
    allowedorigins: # allowed origins for websocket connections (same origin is always allowed)
#      - ".+.example.com"
#      - "otherdomain.com"

database: # for database see (configure database section)
  dialect: postgres
  connection: host=192.168.207.10 port=5432 user=gotify dbname=gotify password=password

defaultuser: # on database creation, gotify creates an admin user
  name: admin # the username of the default user
  pass: admin # the password of the default user
passstrength: 16 # the bcrypt password strength (higher = better but also slower)
uploadedimagesdir: /srv/gotify/images # the directory for storing uploaded images
pluginsdir: /srv/gotify/plugins # the directory where plugin resides
```
- Apache2
```apahe
<VirtualHost *:80>
	ServerName messageme.info
	ServerAlias www.messageme.info
	RewriteEngine On
	RewriteCond %{SERVER_NAME} =messageme.info [OR]
	RewriteCond %{SERVER_NAME} =www.messageme.info
	RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>

<IfModule mod_ssl.c>
<VirtualHost *:443>

	ServerName messageme.info
	ServerAlias www.messageme.info
	ServerAdmin webmaster@messageme.info

	Include /etc/letsencrypt/options-ssl-apache.conf
	SSLCertificateFile /etc/letsencrypt/live/messageme.info/fullchain.pem
	SSLCertificateKeyFile /etc/letsencrypt/live/messageme.info/privkey.pem

	Keepalive On

	RewriteEngine On

	RewriteCond %{HTTP_HOST} ^www\.(.*)$ [NC]
	RewriteRule ^(.*)$ http://%1/$1 [R=301,L]

	RewriteCond %{HTTP:Connection} Upgrade [NC]
	RewriteCond %{HTTP:Upgrade} websocket [NC]
	RewriteRule /stream(.*) ws://127.0.0.1:5000/stream$1 [P,L]

	RequestHeader set X-Forwarded-Proto "https"
	ProxyPreserveHost On

	ProxyPass /stream ws://127.0.0.1:5000/stream retry=0 timeout=5
	ProxyPass / http://127.0.0.1:5000/ retry=0 timeout=5
	ProxyPassReverse / http://127.0.0.1:5000/

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

</VirtualHost>
</IfModule>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
```
