### ISSUE TITLE
Default Login doesn't works

### ISSUE THREAD

**Issue by RobinDev03** [gotify/server#454]
**Can the issue be reproduced with the latest available release? (y/n)**

**Which one is the environment gotify server is running in?**
- [ x ] Docker
<details><summary>Docker startup command or config file here (please mask sensitive information)</summary><br>

```
version: "3"

services:
  gotify:
    image: gotify/server
    ports:
      - 8080:80
    environment:
      - GOTIFY_DEFAULTUSER_PASS=custom
    volumes:
      - "./gotify_files:/app/data"

```
</details>

**Do you have an reverse proxy installed in front of gotify server? (Please select None if the problem can be reproduced without the presense of a reverse proxy)**
- [ x ] Caddy
<details><summary>Reverse proxy configuration (please mask sensitive information)</summary><br>

```
notify.robin-it.group {
        reverse_proxy localhost:8080
}

```
</details>

**On which client do you experience problems? (Select as many as you can see)**
- [ x ] WebUI

**What did you do?**
Try to Login with the default information (admin & admin)

**What did you expect to see?**
to get logged in

**What did you see instead? (Include screenshots, android logcat/request dumps if possible)**
Login-Failure (Login Failed)
