### ISSUE TITLE
Login fail over nginx reverse proxy

### ISSUE THREAD

**Issue by paultroeger** [gotify/server#473]
**Have you read the documentation?**
- [ ] Yes, but it does not include related information regarding my question.
- [x] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [x] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**
I'm having difficulties setting up my nginx reverse proxy. 
The login on gotify.domain.tld does not work (with admin, admin). 
I've read through the documentation and closed issues but I can't seem to find the problem.
I would be very helpful for a pointer.

Here's my nginx config:
```
server {
  listen 443 ssl;

  # Here goes your domain / subdomain
  server_name gotify.domain.tld;

  ssl_certificate path/to/certificate;
  ssl_certificate_key path/to/certificate;

  location / {
    # We set up the reverse proxy
    proxy_pass         http://127.0.0.1:9004/;
    proxy_http_version 1.1;

    # Ensuring it can use websockets
    proxy_set_header   Upgrade $http_upgrade;
    proxy_set_header   Connection "upgrade";
    proxy_set_header   X-Real-IP $remote_addr;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Proto http;
    proxy_redirect     http:// $scheme://;

    # The proxy must preserve the host because gotify verifies the host with the origin
    # for WebSocket connections
    proxy_set_header   Host $http_host;

    # These sets the timeout so that the websocket can stay alive
    proxy_connect_timeout   1m;
    proxy_send_timeout      1m;
    proxy_read_timeout      1m;
  }
}
```

More Info:

<details><summary>docker-compose File:</summary><br><pre>

```
version: '3'
services:
    gotify:
        image: gotify/server
        ports:
            - 9004:9004
            - 9005:9005
        volumes:
            - ./data:/app/data
        restart: unless-stopped
        environment:
            - GOTIFY_SERVER_PORT=9004
            - GOTIFY_SERVER_SSL_PORT=9005
            - GOTIFY_SERVER_SSL_REDIRECTTOHTTPS=false
```
</pre></details>

<details><summary>docker-compose Error Message:</summary><br><pre>
Error #01: you need to provide a valid access token or user credentials to access this api
</pre></details>

<details><summary>Firefox Error:</summary><br><pre>

Status
401
Unauthorized
VersionHTTP/2
Transferred309 B (141 B size)
Referrer Policystrict-origin-when-cross-origin

</pre></details>
