### ISSUE TITLE
Cannot login with default credentials

### ISSUE THREAD

**Issue by Compizfox** [gotify/server#477]
**Have you read the documentation?**
- [x] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [x] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**
I installed Gotify in a Docker container, using the following docker-compose config:

```
version: "3"

services:
  gotify:
    container_name: gotify
    image: gotify/server
    ports:
      - 127.0.0.1:8082:80
    environment:
      - GOTIFY_DEFAULTUSER_NAME=admin
      - GOTIFY_DEFAULTUSER_PASS=foobar
    volumes:
      - "./gotify_data:/app/data"
    restart: unless-stopped
```

I use Apache as a reverse proxy. I followed the "Proxy requests with sub path" example from the documentation.

My issue is that I cannot login with the default credentials I set in the Docker config. I get a "Login failed" everytime I try to login.

**Any errors, logs, or other information that might help us identify your problem**

When trying to login, the Docker container logs this:

```
[GIN] 2022/04/23 - 15:46:48 | 401 |   73.625908ms | 2a02:58:ce:af00:: | POST     "/client"
Error #01: you need to provide a valid access token or user credentials to access this api
```
