### ISSUE TITLE
Gotify behind Traefik can't connect

### ISSUE THREAD

**Issue by sebastienPoussard** [gotify/server#481]
**Have you read the documentation?**
- [x] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [x] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**

I'm trying to set gotify behing my Traefik reverse proxy and get error when trying to connect with the default login on a fresh install.
Tried gotify without Traefik and it works nicely.
In the documentation there is not help regarding using gotify with traefik.
I have tons of services behind Traefik and really have no clues why it is not working, i can see the login page but authentication fails.
in the goty logs : 
```
Error #01: you need to provide a valid access token or user credentials to access this api
```
my docker-compose.yml file is the following : 

```
version: '3'
 
services:
 app:
   image: gotify/server:latest
   container_name: "gotify"
   restart: unless-stopped
   volumes:
     - /data/gotify/data:/app/data
   networks:
     - traefik_gotify
   labels:
     - "traefik.enable=true"
     - "traefik.http.routers.gotify.entrypoints=websecure"
     - "traefik.http.routers.gotify.rule=Host(`gotify.XXXX.com`)"
     - "traefik.http.routers.gotify.tls=true"
     - "traefik.http.routers.gotify.tls.certresolver=myresolver"
     - "traefik.docker.network=traefik_gotify"
networks:
  traefik_gotify:
    external: true
```
Can someone point me into the right direction ?
