### ISSUE TITLE
Gotify with Traefik v2

### ISSUE THREAD

**Issue by mrwormo** [gotify/server#513]
**Have you read the documentation?**
- [x] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [x] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**

Hello all,

I'm having difficulties setting up Gotify with Traefik v2.
I'm running dozen of containers behind Traefik whithout any kind of problems with dynamic config files.

My problem is i can't log in Gotify even the first time with defaults credentials with `401 Unauthorized` response.
Logs in Gotify container doesn't see the `POST` request, so i guess there is a problem with Traefik.

I'm stuck...

**Any errors, logs, or other information that might help us identify your problem**

<details><summary>Docker-compose.yml</summary><br><pre>
 gotify:
   image: gotify/server:latest
   restart: always
   container_name: gotify
   hostname: gotify
   volumes:
     - ../gotify:/app/data
   networks:
     - traefik
</pre></details>

<details><summary>gotify.yml</summary><br><pre>
http:
  services:
    gotify:
      loadBalancer:
        servers:
          - url: "http://gotify"
  routers:
    gotify:
      rule: "Host(`gotify.tld`)"
      entryPoints:
        - "web"
      middlewares:
        - "redirect-to-https@file"
      service: "noop@internal"
    gotify-secure:
      rule: "Host(`gotify.tld`)"
      entryPoints:
        - "websecure"
      middlewares:
        - "hsts@file"
        - "security@file"
        - "compression@file"
        - "admin-users@file"
      service: "gotify@file"
      tls:
        certResolver: letsencrypt-ecdsa
        options: mintls13
</pre></details>

<details><summary>security.yml</summary><br><pre>
http:
  middlewares:
    security:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
          - POST
        accessControlMaxAge: 100
        addVaryHeader: true
        browserXssFilter: true
        contentTypeNosniff: true
        frameDeny: true
        sslRedirect: true
        customFrameOptionsValue: "SAMEORIGIN"
        referrerPolicy: "same-origin"
        permissionsPolicy: "vibrate 'self'"
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        customresponseheaders:
          X-Powered-By: ""
          Server: ""
</pre></details>

**Comment by jmattheis** [comment]
Show the definitions of all the used middlewares (`hsts@file`, `security@file`, `compression@file`, `admin-users@file`).

**Comment by mrwormo** [comment]
> Show the definitions of all the used middlewares (`hsts@file`, `security@file`, `compression@file`, `admin-users@file`).

- hsts.yml
```
http:
  middlewares:
    hsts:
      headers:
        forceSTSHeader: true
        stsSeconds: 315360000
        stsIncludeSubdomains: true
        stsPreload: true
```
- compression.yml
```
http:
  middlewares:
    compression:
      compress:
        excludedContentTypes:
          - "text/event-stream"
```
- admin-users.yml
```
http:
  middlewares:
    admin-users:
      basicAuth:
        users:
          - "user:password"
```
