### ISSUE TITLE
Problem with HTTPS

### ISSUE THREAD

**Issue by solairen** [gotify/server#543]
**Have you read the documentation?**
- [ x ] Yes, but it does not include related information regarding my question.
- [ x ] Yes, but the steps described in the documentation do not work on my machine.
- [ x ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [ x ] Docker

**Describe your problem**
Hi, I have a problem with HTTPS. I've used configuration from the page: https://gotify.net/docs/config and when I start gotify I got an error:

```log
Starting Gotify version 2.1.7@2022-09-11-07:29:06
panic: pq: SSL is not enabled on the server

goroutine 1 [running]:
main.main()
        /proj/app.go:47 +0x36d
Starting Gotify version 2.1.7@2022-09-11-07:29:06
panic: pq: SSL is not enabled on the server

goroutine 1 [running]:
main.main()
        /proj/app.go:47 +0x36d
```

My `docker-compose` config:

```yml
version: "3.9"
services:
  gotify:
    image: gotify/server:2.1.7
    container_name: gotify
    hostname: gotify
    environment:
      - GOTIFY_SERVER_PORT=80
      - GOTIFY_SERVER_KEEPALIVEPERIODSECONDS=0
      - GOTIFY_SERVER_LISTENADDR=""
      - GOTIFY_SERVER_SSL_ENABLED=true
      - GOTIFY_SERVER_SSL_REDIRECTTOHTTPS=true
      - GOTIFY_SERVER_SSL_LISTENADDR=""
      - GOTIFY_SERVER_SSL_PORT=443
      - GOTIFY_SERVER_SSL_CERTFILE=certs/gotify.crt
      - GOTIFY_SERVER_SSL_CERTKEY=certs/gotify.key
      - GOTIFY_SERVER_STREAM_PINGPERIODSECONDS=45
      - GOTIFY_DATABASE_DIALECT=postgres
      - GOTIFY_DATABASE_CONNECTION=host=127.0.0.1 port=5432 user=gotify dbname=gotify password=gotify123
      - GOTIFY_DEFAULTUSER_NAME=gotify
      - GOTIFY_DEFAULTUSER_PASS=gotify123
      - GOTIFY_PASSSTRENGTH=10
      - GOTIFY_UPLOADEDIMAGESDIR=data/images
      - GOTIFY_PLUGINSDIR=data/plugins
      - GOTIFY_REGISTRATION=false
    ports:
      - 8001:80
      - 8443:443
    volumes:
      - gotify-data-volume:/app/data
    restart: unless-stopped
    labels:
      hostname: gotify
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "7"
        labels: "hostname"
```
