### ISSUE TITLE
Caching of message images?

### ISSUE THREAD

**Issue by thehijacker** [gotify/server#544]
**Have you read the documentation?**
- [X] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [X] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**

From home assistant I am sending messages to Gotify when movement around house is detected. Inside message I am also adding URL to the latest camera screenshot. If I use telegram notify, it will cache this image and store it in Telegram cloud. It will always be visible inside Telegram. If I use Gotify it just adds the URL to the image inside the message, which fails to load outside my LAN.

Docker config:

```
  gotify:
    image: gotify/server
    container_name: gotify
    ports:
      - 14880:80
    environment:
      - TZ=Europe/Ljubljana
    volumes:
      - "/mnt/usb_4/Docker/Gotify/data:/app/data"
      - "/mnt/usb_4/Docker/Gotify/config:/etc/gotify"

```

Gotify home assistant notification definition:

```
notify:
  - name: gotify
    platform: rest
    resource: https://gotify.test.com/message
    method: POST_JSON
    headers:
      X-Gotify-Key: !secret gotify_key_ha
    message_param_name: message
    title_param_name: title
    data:
      extras:
        client::display:
          contentType: "text/markdown"
```

Example of Telegram notification call:

```
service: notify.telegram_andrej
data:
  title: This is a title
  message: This is a message
  data:
    title: Send an images
    message: That's an example that sends an image.
    photo:
      - url: http://192.168.28.55:5000/api/vhod/latest.jpg
        caption: Vhod
      - url: http://192.168.28.55:5000/api/balkon/latest.jpg
        caption: Balkon
      - url: http://192.168.28.55:5000/api/spredaj/latest.jpg?timestamp=1
        caption: Spredaj
```

Example of Gotify notification call:

```
service: notify.gotify
data:
  title: Zaznano gibanje na vhodu
  message: |-
    *Kamera vhod:*
    ![Camera Image](http://192.168.28.55:5000/api/vhod/latest.jpg)
    *Kamera balkon:*
    ![Camera Image](http://192.168.28.55:5000/api/balkon/latest.jpg)
    *Kamera spredaj:*
    ![Camera Image](http://192.168.28.55:5000/api/spredaj/latest.jpg?timestamp=1)
```

And how it looks:

![image](https://user-images.githubusercontent.com/13857043/214312552-8215f807-eb88-4150-b54c-3633f844f3e5.png)

URL changed from http to https and it tries to load: https://192.168.28.55:5000/api/vhod/latest.jpg

Can Gotify cache this somehow? So it gets uploaded to server on push call?

Thank you.
