### ISSUE TITLE
I am not getting https on for my gotify server.

### ISSUE THREAD

**Issue by arvindjkhr** [gotify/server#556]
**Have you read the documentation?**
- [X] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and wants clarification.

**You are setting up gotify in**
- [ ] Docker
- [X] Linux native platform
- [ ] Windows native platform

**Describe your problem**
I am not getting https on for my gotify server.

my config is as follows.

```
_[root@gotify data]# cat /etc/gotify/config.yml
server:
  keepaliveperiodseconds: 0 # 0 = use Go default (15s); -1 = disable keepalive; set the interval in which keepalive packets will be sent. Only change this value if you know what you are doing.
  listenaddr: "" # the address to bind on, leave empty to bind on all addresses
  port: 80 # the port the HTTP server will listen on
  ssl:
    enabled: false # if https should be enabled
    redirecttohttps: true # redirect to https if site is accessed by http
    listenaddr: "" # the address to bind on, leave empty to bind on all addresses
    port: 443 # the https port
    certfile: /etc/gotify/cert.pem # the cert file (leave empty when using letsencrypt)
    certkey: /etc/gotify/cert.key # the cert key (leave empty when using letsencrypt)
    letsencrypt:
      enabled: false # if the certificate should be requested from letsencrypt
      accepttos: false # if you accept the tos from letsencrypt
      cache: data/certs # the directory of the cache from letsencrypt
  responseheaders: # response headers are added to every response (default: none)
    X-Custom-Header: "Push Notifications"_**
```
