### ISSUE TITLE
acme/autocert: host not configured in HostWhitelist

### ISSUE THREAD

**Issue by Snify89** [gotify/server#558]
**Can the issue be reproduced with the latest available release? (y/n)**
y

**Which one is the environment gotify server is running in?**
- [x] Docker
- [x] Linux machine
<details><summary>Docker startup command or config file here (please mask sensitive information)</summary><br>

```
version: "3"

services:
  gotify:
    restart: always
    image: gotify/server
    ports:
      - 80:80
      - 443:443
    environment:
      - GOTIFY_DEFAULTUSER_PASS=mypass
      - GOTIFY_SERVER_SSL_ENABLED=true
      - GOTIFY_SERVER_SSL_LETSENCRYPT_ENABLED=true
      - GOTIFY_SERVER_SSL_LETSENCRYPT_ACCEPTTOS=true
      - GOTIFY_SERVER_SSL_LETSENCRYPT_HOSTS=- myhost.com\n- www.myhost.com
    volumes:
      - "./gotify_data:/app/data"
```
</details>

**Do you have an reverse proxy installed in front of gotify server? (Please select None if the problem can be reproduced without the presense of a reverse proxy)**
- [x] None
- [ ] Nginx
- [ ] Apache
- [ ] Caddy
<details><summary>Reverse proxy configuration (please mask sensitive information)</summary><br>

```

```
</details>

**On which client do you experience problems? (Select as many as you can see)**
- [x] WebUI
- [x] gotify-cli
- [ ] Android Client 
- [ ] 3rd-party API call (Please include your code)

**What did you do?**
Tried to use the let's encrypt feature 

**What did you expect to see?**
Working SSL 

**What did you see instead? (Include screenshots, android logcat/request dumps if possible)**
docker logs 
2023/03/29 13:18:11 http: TLS handshake error from someip: acme/autocert: host "myhost.com" not configured in HostWhitelist
other errors:
http: TLS handshake error from someip: acme/autocert: server name component count invalid
http: TLS handshake error from someip: acme/autocert: missing server name

Also: no certs folder in /app/data

**Comment by najtin** [comment]
@Snify89  

TDLR:

Instead of `GOTIFY_SERVER_SSL_LETSENCRYPT_HOSTS=- myhost.com\n- www.myhost.com` 

do 
`GOTIFY_SERVER_SSL_LETSENCRYPT_HOSTS='["myhost.com", "www.myhost.com"]'` 

---

Detailed explanation 

The problem originates in that all items in the list in yaml under environment are interpreted as json. Here is the config above as json. This is just another way to convey the same information:

```json
{
    "version": "3",
    "services": {
        "gotify": {
            "restart": "always",
            "image": "gotify/server",
            "ports": [
                "80:80",
                "443:443"
            ],
            "environment": [
                "GOTIFY_DEFAULTUSER_PASS=mypass",
                "GOTIFY_SERVER_SSL_ENABLED=true",
                "GOTIFY_SERVER_SSL_LETSENCRYPT_ENABLED=true",
                "GOTIFY_SERVER_SSL_LETSENCRYPT_ACCEPTTOS=true",
                "GOTIFY_SERVER_SSL_LETSENCRYPT_HOSTS=- myhost.com\\n- asdf"
            ],
            "volumes": [
                "./gotify_data:/app/data"
            ]
        }
    }
}
```

This means, that configor (the module that gotify uses to parse the env) gets the escaped `"\\n"` instead of `"\n"`

@jmattheis  **IMHO this is not a bug in gotify and also not a bug docker or configor.** This is the expected behaivour of docker as detailed in the [manual](https://docs.docker.com/compose/how-tos/environment-variables/set-environment-variables/).

The manually also provides another solution in addition to the above: Use mapping syntax instead of listing syntax.

```
version: "3"

services:
  gotify:
    restart: always
    image: gotify/server
    ports:
      - 80:80
      - 443:443
    environment:
      GOTIFY_DEFAULTUSER_PASS: "mypass"
      GOTIFY_SERVER_SSL_ENABLED: "true"
      GOTIFY_SERVER_SSL_LETSENCRYPT_ENABLED: "true"
      GOTIFY_SERVER_SSL_LETSENCRYPT_ACCEPTTOS: "true"
      GOTIFY_SERVER_SSL_LETSENCRYPT_HOSTS: "- myhost.com\n- www.myhost.com"
    volumes:
      - "./gotify_data:/app/data"
```
