### ISSUE TITLE
Accept priority as string

### ISSUE THREAD

**Issue by lezruk** [gotify/server#642]
**Is your feature request related to a problem? Please describe.**
Home-Assistant notify service with POST_JSON type always sends priority as sting in resulting JSON due to templating engine (similar how ansible jinja templating works), that is not accepted by gotify server with 400 bad requests, as it accepts strict integer value for priority only

**Describe the solution you'd like**
gotify server to accept priority as string, and throw an error only if string value is not castable to integer

**Describe alternatives you've considered**
No real alernativies found so far, only hardcoding particular value/default priority which doesn't serve the purpose of prioirty differentiation within single app messages

**Additional context**
N/A

**Comment by LaurenceJJones** [comment]
Hey 👋🏻 

Looking at [home assistant docs](https://www.home-assistant.io/docs/configuration/templating/#important-template-rules) they provide a link to -> https://jinja.palletsprojects.com/en/latest/templates/#jinja-filters.int

I dont know what the template look like but I guess you should be able to type conversion?

**Comment by lezruk** [comment]
All these filters are fine, but problem is that POST_JSON result is ALWAYS sent in quotes, which is interpreted as string. Thus gotify rejects it.

**Comment by jmattheis** [comment]
You can set the priority like this in home assistent (also included markdown support):
```yml
notify:
  - name: gotify_high
    platform: rest
    resource: https://gotify.example.org/message
    method: POST_JSON
    headers:
      X-Gotify-Key: AsQHYA96LH90.RT
    message_param_name: message
    title_param_name: title
    data:
      priority: 10
      extras:
        client::display:
          contentType: "text/markdown"
```

**Comment by lezruk** [comment]
Appreciate your answer, hardcoding value in data.extras works. Idea though is to avoid hardcoding and send priority as a value for individual message call within same service. Therefore I opened this request for evaluation.

**Comment by jmattheis** [comment]
How do I manually trigger an alert with priority in home assistant? developer-tools/service doesn't have a priority.

**Comment by lezruk** [comment]
> How do I manually trigger an alert with priority in home assistant? developer-tools/service doesn't have a priority.

There is target parameter for notification service, that you can map to priority for gotify call. But again internally that is sent in JSON in quotes and doesn't work. Other option would be sending payload as fields in POST call, yet in this case markdown is lost as gotify doesn't support extras parameters without json. I saw somewhere here request to implement extras fields params i gotify but that was not done

**Comment by aagit** [comment]
Same here, I also tried to pass priority as string and didn't work. Corollary problem is the click url needs to be null in json to be ignored by the android client, the empty string should be treated like null.

**Comment by nienow** [comment]
I found a great solution to using Gotify in home assistant. Instead of using notify, I'm using a rest_command, and a script. This lets me define the priority field as a number between 1 and 10. You can call the gotify script in automatons and it will generate fields in the UI based on your definitions.

```
rest_command:
  gotify_command:
    url: https://my_gotify_server/message
    method: POST
    headers:
      authorization: 'Bearer MY_TOKEN'
      content-type: 'application/json'
    payload: "{{payload}}"
          
script:
  gotify:
    alias: Gotify Notification
    fields:
      message:
        name: Message
        required: true
        selector:
          text:
      title:
        name: Title
        required: false
        selector:
          text:
      priority:
        name: Priority
        default: 5
        selector:
          number:
            min: 1
            max: 10
    sequence:
      - service: rest_command.gotify_command
        data:
          payload: >-
            {{
              {
                "message": message,
                "title": title | default("")
                "priority": priority | default(5)
              } | tojson
            }}
```
