### ISSUE TITLE
Fails to run on Raspberry Pi 5

### ISSUE THREAD

**Issue by azchohfi** [gotify/server#670]
**Can the issue be reproduced with the latest available release? (y/n)** Y

**Which one is the environment gotify server is running in?**
- [X] Docker
- [ ] Linux machine
- [x] Windows machine
<details><summary>Docker startup command or config file here (please mask sensitive information)</summary><br>

```
  gotify:
    image: gotify/server-arm7
    container_name: gotify
    ports:
      - 8080:80
    environment:
      - GOTIFY_DEFAULTUSER_PASS=custom
    volumes:
      - ./storage:/app/data
```
</details>

**Do you have an reverse proxy installed in front of gotify server? (Please select None if the problem can be reproduced without the presense of a reverse proxy)**
- [X] None
- [ ] Nginx
- [ ] Apache
- [ ] Caddy
<details><summary>Reverse proxy configuration (please mask sensitive information)</summary><br>

```

```
</details>

**On which client do you experience problems? (Select as many as you can see)**
- [X] WebUI
- [ ] gotify-cli
- [ ] Android Client 
- [ ] 3rd-party API call (Please include your code)

**What did you do?**
Run:
`docker-compose up gotify`

**What did you expect to see?**
gotify running fine.

**What did you see instead? (Include screenshots, android logcat/request dumps if possible)**
I see:
```
Attaching to gotify
gotify  | ./gotify-app: error while loading shared libraries: libresolv.so.2: ELF load command address/offset not page-aligned
gotify exited with code 127
```
