### ISSUE TITLE
Markdown URLs not rendering correctly. 

### ISSUE THREAD

**Issue by Nillth** [gotify/server#725]
**Can the issue be reproduced with the latest available release? y**

**Which one is the environment gotify server is running in?**
- [x] Docker
- [ ] Linux machine
- [ ] Windows machine
<details><summary>Docker startup command or config file here (please mask sensitive information)</summary><br>

```
services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    container_name: changedetection
    hostname: changedetection
    volumes:
      - changedetection-data:/datastore
    labels:
      - "traefik.http.services.${SVCName}.loadbalancer.server.port=5000"
      # - "com.centurylinklabs.watchtower.enable=true"
    env_file:
      - .env
    environment:
      - WEBDRIVER_URL="http://browser-chrome:4444/wd/hub"
    networks:
      - traefik
      - default    
    extends:
      file: ../common-services-app.yml
      service: app
    restart: always
  browser-chrome:
    hostname: browser-chrome
    image: selenium/standalone-chrome-debug:3.141.59
    volumes:
        - /dev/shm:/dev/shm
    restart: unless-stopped
    networks:
      - default
networks:
  traefik:
    external: true
  default:
volumes:
  changedetection-data:
```
</details>

**Do you have an reverse proxy installed in front of gotify server? (Please select None if the problem can be reproduced without the presense of a reverse proxy)**
- [ ] None
- [x] Nginx
- [ ] Apache
- [ ] Caddy
- [x] Traefik 
<details>Internet -> Nginx -> Traefik -> ChangeDetection Docker
</details>

**On which client do you experience problems? (Select as many as you can see)**
- [x] WebUI
- [ ] gotify-cli
- [ ] Android Client 
- [ ] 3rd-party API call (Please include your code)

**What did you do?**

Notification sent to server correctly. 

**What did you expect to see?**

The markdown to be rendered correctly with a clickable URL 

![image](https://github.com/user-attachments/assets/9fca51d7-30d4-4188-88fd-af3e8d9d78aa)

**What did you see instead? (Include screenshots, android logcat/request dumps if possible)**

In the Web App

![image](https://github.com/user-attachments/assets/08882cac-e2c7-491a-9f05-3dcad684e086)

vs the Android App which was [sort of fixed](https://github.com/gotify/android/issues/136) but still not rendering correctly 
![image](https://github.com/user-attachments/assets/4e6975e3-0338-4970-b164-7e2a420a985a)
