### ISSUE TITLE
Missing SSL certificate store in Docker image?

### ISSUE THREAD

**Issue by mmomjian** [gotify/server#731]
Hello, I am trying to setup the gotify2telegram bot but kept getting x509 cert errors for api.telegram.org in the logs. I dug further and I am not able to validate any external SSL certs using the command line with the latest arm64 docker image of Gotify. Is this a known issue and is there any workaround?

**Can the issue be reproduced with the latest available release? yes**

**Which one is the environment gotify server is running in?**
- [x ] Docker
- [ ] Linux machine
- [ ] Windows machine
<details><summary>Docker startup command or config file here (please mask sensitive information)</summary><br>

```
  gotify2:
    image: gotify/server-arm64
    ports:
      - 22480:80   
    environment:
      - GOTIFY_DEFAULTUSER_PASS=passwordnamehere
    volumes:
      - "/home/ubuntu/gotify_test:/app/data"
      - '${dockerdata}/docker-lib/curl:/curl:ro'

```
</details>

**Do you have an reverse proxy installed in front of gotify server? (Please select None if the problem can be reproduced without the presense of a reverse proxy)**
- [x ] None

**On which client do you experience problems? (Select as many as you can see)**
Docker shell

**What did you do?**
Run a static curl command, sourced from https://github.com/moparisthebest/static-curl

**What did you expect to see?**
Ability to curl outside websites

**What did you see instead? (Include screenshots, android logcat/request dumps if possible)**
```
root@oracle-3:/home/ubuntu# docker exec -it compose-all-oci3-gotify2-1 bash
root@3992d96d30c3:/app# /curl https://google.com
curl: (77) error setting certificate verify locations:  CAfile: /etc/ssl/certs/ca-certificates.crt CApath: none
```
