### ISSUE TITLE
UI not loading as of today and no error in logs.

### ISSUE THREAD

**Issue by NightHawkATL** [gotify/server#753]
**Can the issue be reproduced with the latest available release? (y/n)**
Yes, I have the "latest" release and it has not been updated or changed since last year.
![image](https://github.com/user-attachments/assets/06d59eb7-4d48-4c23-8933-074fb7888806)

**Which one is the environment gotify server is running in?**
- [X] Docker
- [ ] Linux machine
- [ ] Windows machine
<details><summary>Docker startup command or config file here (please mask sensitive information)</summary><br>

```
services:
  gotify:
    image: gotify/server:latest
    network_mode: bridge
    container_name: gotify
    restart: unless-stopped
    ports:
      - 9008:80
    environment:
      - GOTIFY_DEFAULTUSER_NAME=admin
      - GOTIFY_DEFAULTUSER_PASS=SOMEPASSWORD
      - TZ=America/New_York
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    volumes:
      - "/portainer/Files/AppData/Config/gotify/:/app/data"

```
</details>

**Do you have an reverse proxy installed in front of gotify server? (Please select None if the problem can be reproduced without the presense of a reverse proxy)**
- [X] None
- [ ] Nginx
- [ ] Apache
- [ ] Caddy
<details><summary>Reverse proxy configuration (please mask sensitive information)</summary><br>
I do have a reverse proxy and do use it for Gotify but if the local instance isn't working, neither is the proxied one. I have tried both the local instance and the proxied instance and neither are working right now. I use Zoraxy for my reverse proxy ATM.
```

```
</details>

**On which client do you experience problems? (Select as many as you can see)**
- [X] WebUI
- [ ] gotify-cli
- [ ] Android Client 
- [ ] 3rd-party API call (Please include your code)

**What did you do?**
I have tried a reboot of Docker and of the host VM. Nothing else on the physical host or even the docker instance is failing.
**What did you expect to see?**
I expected it to load without issue.
**What did you see instead? (Include screenshots, android logcat/request dumps if possible)**
![image](https://github.com/user-attachments/assets/0686d25a-101e-40f7-8e28-23473bd29dd1)
![image](https://github.com/user-attachments/assets/c218e5a4-4327-4e34-8f23-158f25d9d371)
