### ISSUE TITLE
panic: dial tcp [::1]:5432: connect: connection refused

### ISSUE THREAD

**Issue by drifter75** [gotify/server#769]
with versions 2.6.0 & 2.6.1 deployment fails with below error.

```
Starting Gotify version 2.6.0@2024-11-15-19:19:19
panic: dial tcp [::1]:5432: connect: connection refused

goroutine 1 [running]:
main.main()
        /src/gotify/app.go:47 +0x39c
Starting Gotify version 2.6.0@2024-11-15-19:19:19
panic: dial tcp [::1]:5432: connect: connection refused
```

same compose works fine with 2.5.0

using postgres as DB.

**Comment by drifter75** [comment]
gotify/server:2.5.0 & gotify/server:2.6.1 were the images used, assume these are the official ones.

[gotify/server:2.5.0(working)](https://github.com/drifter75/special-eureka/issues/1#issue-2851447353)
[gotify/server:2.6.1(NotWorking)](https://github.com/drifter75/special-eureka/issues/2#issue-2851464232)

**Comment by eternal-flame-AD** [comment]
Very likely https://github.com/gotify/website/issues/91 , your docker compose environment variables must be entirely quoted or written in the key-value (dictionary) format, see https://github.com/gotify/website/issues/91#issuecomment-2485958555 for the fix and explanation. 

It worked before because of a silent 'repair' mechanism present in our previous configuration parsing logic that was removed. Now the database URL wasn't being interpreted correctly.

**Comment by drifter75** [comment]
Thanks 👍 resolved by removing the quotes on connection properties.

Changed:
```yml
    image: gotify/server:2.6.1
    environment:
      - TZ='Europe/Berlin'
      - GOTIFY_DATABASE_DIALECT=postgres
      - GOTIFY_DATABASE_CONNECTION="host=postgres15 port=5432 user=gotify dbname=gotify password='XXX' sslmode=disable"
```

to:

```yml
    image: gotify/server:2.6.1
    environment:
      - TZ='Europe/Berlin'
      - GOTIFY_DATABASE_DIALECT=postgres
      - GOTIFY_DATABASE_CONNECTION=host=postgres15 port=5432 user=gotify dbname=gotify password='XXX' sslmode=disable
```
