### ISSUE TITLE
WebSocket: ReadError read tcp 172.XXXX:8081->172.19.0.2:49230: i/o timeout

### ISSUE THREAD

**Issue by ThierryIT** [gotify/server#771]
**Can the issue be reproduced with the latest available release? (y/n)** Yes using version 2.6.1

**Which one is the environment gotify server is running in?** 
- [ X] Docker
- [ ] Linux machine
- [ ] Windows machine
<details><summary>Docker startup command or config file here (please mask sensitive information)</summary><br>

```
services:
  gotify:
    image: gotify/server:2.6.1
    container_name: gotify
    volumes:
      - $BASE/gotify:/app/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    command:
      - "--host=tcp://g-docker-socket-proxy:2375"
    security_opt:
      - no-new-privileges:true
    depends_on:
      - dockerproxy
    networks:
      - dagga-boys
      - socket-g
    environment:
      - TZ=Europe/Helsinki
      #- GOTIFY_SERVER_PORT=8081
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gotify.entrypoints=http-external"
      - "traefik.http.routers.gotify.rule=Host(`gotify.domain.tld`)"
      - "traefik.http.middlewares.gotify-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.gotify.middlewares=gotify-https-redirect"
      - "traefik.http.routers.gotify-secure.entrypoints=https-external"
      - "traefik.http.routers.gotify-secure.rule=Host(`gotify.domain.tld`)"
      - "traefik.http.routers.gotify-secure.tls=true"
      - "traefik.http.routers.gotify-secure.service=gotify"
      - "traefik.http.services.gotify.loadbalancer.server.port=8081"
      - "traefik.docker.network=mynet"


  dockerproxy:
    image: wollomatic/socket-proxy:1.5.4
    container_name: g-docker-socket-proxy
    command:
      - -loglevel=info # change to info in prod
      - -allowfrom=gotify
      - -listenip=0.0.0.0
      - -shutdowngracetime=5
      - -allowGET=/containers/.*
      - -watchdoginterval=600
      - -stoponwatchdog
    restart: unless-stopped
    read_only: true
    mem_limit: 64M
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    user: 65534:110 # change gid from 998 to the gid of the docker group on your host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - socket-g
networks:
  socket-g:
    internal: true
    attachable: false
  mynet:
    external: true
```
</details>

**Do you have an reverse proxy installed in front of gotify server? (Please select None if the problem can be reproduced without the presense of a reverse proxy)**
- [ ] None
- [ ] Nginx
- [ ] Apache
- [ ] Caddy
- [X ] Traefik
<details><summary>Reverse proxy configuration (please mask sensitive information)</summary><br>

```

```
</details>

**On which client do you experience problems? (Select as many as you can see)**
- [ ] WebUI
- [ ] gotify-cli
- [ ] Android Client 
- [ ] 3rd-party API call (Please include your code)
- [X ] Access to Gotify from Internet

**What did you do?**
https://gotify.domain.tld
**What did you expect to see?**
Login page
**What did you see instead? (Include screenshots, android logcat/request dumps if possible)**
Bad gateway Error code 502
Visit [cloudflare.com](https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=gotify.dagga-boys.org) for more information.
2025-02-16 16:17:00 UTC
