### ISSUE TITLE
Gotify access from a docker container

### ISSUE THREAD

**Issue by gmaila** [gotify/server#788]
**Have you read the documentation?**
- [x] Yes, but it does not include related information regarding my question.
- [ ] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and want clarification.

**You are setting up gotify in**
- [x] Docker
- [ ] Linux native platform
- [ ] Windows native platform

**Describe your problem**
I have a Debian VM running different docker web services ; all behing traefick as a reverse proxy.
When accessing gotify from another machine (as in https://gotify.mydomain), it works fine
When accessing gotify from another docker container on said Debian VM with the same URL, I get a 403 forbidden answer (and no trace on logs).
The only way I was able to access gotify is have it run on the same docker network as the containers that need to reach gotify

`docker-compose.yml`
```
version: "3"
networks:
   mynet:
     external:
        name: some_network
services:
  gotify:
    image: gotify/server
    container_name: gotify
    ports:
      - 8070:80
    restart: always
    networks:
       - mynet
    environment:
      - GOTIFY_DEFAULTUSER_PASS=ADMIN
      - GOTIFY_SERVER_STREAM_ALLOWEDORIGINS=["- .*"]
      - GOTIFY_SERVER_TRUSTEDPROXIES=[192.168.0.63/24]
      - GOTIFY_SERVER_CORS_ALLOWORIGINS=["- .*"]
      - GOTIFY_SERVER_CORS_ALLOWMETHODS=[GET, POST]
```
Hereafter a curl from a container on same machine but different network.

`curl "https://gotify.mydomain/message?token=AQHXz-da5G.0K7M" -F "title=geo" -F "message=geo" -F "priority=5" -v`
```
* Host gotify.mydomain:443 was resolved.
* IPv6: (none)
* IPv4: 192.168.0.63
*   Trying 192.168.0.63:443...
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: /etc/ssl/certs
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256 / x25519 / RSASSA-PSS
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=mydomain
*  start date: Mar 17 22:07:48 2025 GMT
*  expire date: Jun 15 22:07:47 2025 GMT
*  subjectAltName: host "gotify.mydomain" matched cert's "*.mydomain"
*  issuer: C=US; O=Let's Encrypt; CN=R10
*  SSL certificate verify ok.
*   Certificate level 0: Public key type RSA (4096/152 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 1: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 2: Public key type RSA (4096/152 Bits/secBits), signed using sha256WithRSAEncryption
* Connected to gotify.mydomain (192.168.0.63) port 443
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://gotify.mydomain/message?token=AQHXz-da5G.0K7M
* [HTTP/2] [1] [:method: POST]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: gotify.mydomain]
* [HTTP/2] [1] [:path: /message?token=AQHXz-da5G.0K7M]
* [HTTP/2] [1] [user-agent: curl/8.12.1]
* [HTTP/2] [1] [accept: */*]
* [HTTP/2] [1] [content-length: 364]
* [HTTP/2] [1] [content-type: multipart/form-data; boundary=------------------------LrceHAI0BxFqiWHJqfbv85]
> POST /message?token=AQHXz-da5G.0K7M HTTP/2
> Host: gotify.mydomain
> User-Agent: curl/8.12.1
> Accept: */*
> Content-Length: 364
> Content-Type: multipart/form-data; boundary=------------------------LrceHAI0BxFqiWHJqfbv85
>
* upload completely sent off: 364 bytes
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
< HTTP/2 403
< permissions-policy: accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), vr=(), interest-cohort=()
< referrer-policy: same-origin
< x-content-type-options: nosniff
< x-robots-tag: none,noarchive,nosnippet,notranslate,noimageindex,
< x-xss-protection: 1; mode=block
< content-length: 9
< date: Sun, 06 Apr 2025 21:02:27 GMT
<
```
I get the feeling it's GOTIFY_SERVER_CORS_ALLOWORIGINS related but I'm stuck.

Thanks
