### ISSUE TITLE
Markdown not working

### ISSUE THREAD

**Issue by scropion86** [gotify/server#797]
**Can the issue be reproduced with the latest available release? (y/n)** 
Y

**Which one is the environment gotify server is running in?**
- [x] Docker 
- [ ] Linux machine
- [ ] Windows machine
<details><summary>Docker startup command or config file here (please mask sensitive information)</summary><br>

```
version: "3.8"

services:
  gotify:
    image: gotify/server:latest
    container_name: gotify
    ports:
      - "177:177"
    volumes:
      - gotify_data:/app/data
    environment:
      - GOTIFY_SERVER_PORT=177
      - GOTIFY_SERVER_SSL_ENABLED=false
      - GOTIFY_SERVER_SSL_REDIRECT=false
    restart: unless-stopped

volumes:
  gotify_data:


```
</details>

**Do you have an reverse proxy installed in front of gotify server? (Please select None if the problem can be reproduced without the presense of a reverse proxy)**

**tried both with and without reverse proxy same result**

- [ ] None
- [X] Nginx - using [nginx-proxy-manager ](https://github.com/NginxProxyManager/nginx-proxy-manager)
- [ ] Apache
- [ ] Caddy

![Image](https://github.com/user-attachments/assets/b9d89fc0-95d7-44c0-9cbc-58e091fd33b8)

![Image](https://github.com/user-attachments/assets/05ae71b7-2191-43e6-9b0f-0536fcd13971)

<details><summary>Reverse proxy configuration (please mask sensitive information)</summary><br>

```

```
</details>

**On which client do you experience problems? (Select as many as you can see)**
- [X] WebUI
- [ ] gotify-cli
- [X] Android Client 
- [ ] 3rd-party API call (Please include your code)

**What did you do?**
```

curl --location 'myURL/message' \
--header 'X-Gotify-Key: KEY' \
--header 'Content-Type: application/json' \
--data '{

  "message": "**Update!** was successfully finished.",
  "priority": 7,
  "title": "Hello notification"
}'
```

**What did you expect to see?**

![Image](https://github.com/user-attachments/assets/b4ce1d11-cb6b-4a15-9b00-07cb1a894f5f)

![Image](https://github.com/user-attachments/assets/2649cedc-776b-45c6-b5cd-9822b39b2c1f)

**What did you see instead? (Include screenshots, android logcat/request dumps if possible)**

Normal rendered markdown

![Image](https://github.com/user-attachments/assets/85f05b23-6f70-4679-bab6-a05d768a166d)
