### ISSUE TITLE
Expected HTTP 101 response but was '403 forbidden'

### ISSUE THREAD

**Issue by FabioTavernini** [gotify/server#805]
**Have you read the documentation?**
- [x] Yes, but it does not include related information regarding my question.
- [x] Yes, but the steps described in the documentation do not work on my machine.
- [ ] Yes, but I am having difficulty understanding it and want clarification.

**You are setting up gotify in**
- [x] Docker
- [ ] Linux native platform
- [ ] Windows native platform
- [x] Kubernetes

**Describe your problem**
i get this error from android client app:
``` java.net.ProtocolException: Expected HTTP 101 response but was '403 Forbidden' ```
Im trying to setup Gotify behind contour ingress controller like this:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gotify-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-dns"
spec:
  ingressClassName: contour
  rules:
    - host: gotify.mydomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gotify
                port:
                  number: 80
  tls:
    - hosts:
        - gotify.mydomain.com
      secretName: gotify-tls-secret

```

The Service looks like this:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: gotify
spec:
  selector:
    app: gotify
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

```
and the deployment (i tried multiple variants with the env vars):
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotify
  labels:
    app: gotify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotify
  template:
    metadata:
      labels:
        app: gotify
    spec:
      containers:
        - name: gotify
          image: gotify/server:latest

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          ports:
            - containerPort: 80
          env:
            - name: TZ
              value: "Europe/Berlin"

            # Core server settings
            - name: GOTIFY_DEFAULTUSER_NAME
              value: "admin"
            - name: GOTIFY_DEFAULTUSER_PASS
              value: "admin"
            - name: GOTIFY_REGISTRATION
              value: "false"

            # Listen settings (defaults are fine here)
            - name: GOTIFY_SERVER_LISTENADDR
              value: ""
            - name: GOTIFY_SERVER_KEEPALIVEPERIODSECONDS
              value: "0"
            - name: GOTIFY_SERVER_CORS_ALLOWORIGINS
              value: '[".*"]'

            # TLS is disabled, Contour terminates HTTPS
            - name: GOTIFY_SERVER_SSL_ENABLED
              value: "false"
            - name: GOTIFY_SERVER_SSL_REDIRECTTOHTTPS
              value: "false"

            - name: GOTIFY_SERVER_RESPONSEHEADERS
              value: '{"X-Debug-Proxy": "true"}'

            # Reverse proxy awareness
            - name: GOTIFY_SERVER_TRUSTEDPROXIES
              value: '["0.0.0.0/0"]'

            # CORS & headers
            - name: GOTIFY_SERVER_CORS_ALLOWMETHODS
              value: "[GET, POST]"
            - name: GOTIFY_SERVER_CORS_ALLOWHEADERS
              value: "[X-Gotify-Key, Authorization]"
            - name: GOTIFY_SERVER_STREAM_PINGPERIODSECONDS
              value: "45"
            - name: GOTIFY_SERVER_STREAM_ALLOWEDORIGINS
              value: '[".*"]'

          volumeMounts:
            - name: gotify-data
              mountPath: /app/data

      volumes:
        - name: gotify-data
          persistentVolumeClaim:
            claimName: gotify-data-pvc

```
**Any errors, logs, or other information that might help us identify your problem**

complete logs from android app:
```
2025-06-15 22:26:29.760 INFO: Entering LogsActivity
2025-06-15 22:26:27.356 INFO: Loading more messages for -1
2025-06-15 22:26:27.347 INFO: Entering MessagesActivity
2025-06-15 22:26:27.308 INFO: WebSocket: scheduling a restart in 60 second(s) (via alarm manager)
2025-06-15 22:26:27.306 ERROR: WebSocket(31): failure StatusCode: 403 Message: Forbidden: java.net.ProtocolException: Expected HTTP 101 response but was '403 Forbidden'
	at okhttp3.internal.ws.RealWebSocket.checkUpgradeSuccess$okhttp(RealWebSocket.kt:224)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:170)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
2025-06-15 22:26:27.301 INFO: Server version: 2.6.3@2025-04-27-09:10:38
2025-06-15 22:26:27.240 INFO: WebSocket: Network available, reconnect if needed.
2025-06-15 22:26:27.237 INFO: WebSocket(31): starting...
2025-06-15 22:26:27.235 INFO: Starting WebSocketService
2025-06-15 22:26:27.226 INFO: Authenticated as admin
2025-06-15 22:26:27.118 INFO: Entering InitializationActivity
2025-06-15 22:26:21.371 INFO: Entering LogsActivity
2025-06-15 22:26:17.297 INFO: Entering LogsActivity
2025-06-15 22:26:02.492 INFO: Entering LogsActivity
2025-06-15 22:25:46.747 INFO: Entering LogsActivity
2025-06-15 22:25:40.564 INFO: Logs cleared
```

Ex: `docker-compose.yml`, `nginx.conf`, android logcat, browser requests, etc.
Pod Logs say:
```
Starting Gotify version 2.6.3@2025-04-27-09:10:38
Started listening for plain connection on tcp [::]:80
2025-06-15T23:02:05+02:00 | 200 |     636.234µs |   1.2.3.4 | GET      "/current/user"
```
I can log in on the Android phone (Samsung Galaxy S22 Ultra) just fine, but when the app is open in the background, I get the notification "Error Forbidden" (see logs) trying to reconnect.

should i open this issue in android app repo or am i in the right place here?

Would be awesome if someone can point me in the right direction :)

**Comment by eternal-flame-AD** [comment]
Have you checked does the web UI work without the WebSocket warning?

**Comment by FabioTavernini** [comment]
Yes, i can access the web UI just fine, Login Works, API works, i also see the phone as Device.

**Comment by eternal-flame-AD** [comment]
Hmmmm, I have two theories. 

1. do you have some sort of layer 7 firewall in between (Cloudflare, Vercel, over the counter WAFs, etc) that might be making "sophisticated" decisions to block a request like based on user agent? The reason why I suspect that is you mention the Pod Log but I never see Gotify explicitly returned 403, I assume you should see that request in the normal flow like you observed on your browser.
2. is the hostname you put in and the request handling path exactly the same (from what I read, you point your DNS at your server and it goes to ingress and then Gotify)? If your browser uses one hostname but you connected with another hostname on the phone it might have raised some CORS eyebrows on the server side.

**Comment by FabioTavernini** [comment]
I Think i got it, since the error was from websockets, i tried out a httpproxy (where i can allow websockets specifically) resource instead of ingress:

```yaml
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: gotify
  namespace: gotify
spec:
  ingressClassName: contour
  virtualhost:
    fqdn: gotify.mydomain.com
    tls:
      secretName: gotify-tls-secret
  routes:
    - conditions:
        - prefix: /
      enableWebsockets: true
      services:
        - name: gotify
          port: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gotify-cert
  namespace: gotify
spec:
  secretName: gotify-tls-secret
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  commonName: gotify.mydomain.com
  dnsNames:
    - gotify.mydomain.com
```
Found this contour doc page for it:
[https://projectcontour.io/docs/v1.10.0/config/websockets/](https://projectcontour.io/docs/v1.10.0/config/websockets/)

This seemed to tork on test infra, ill try it later in prod.

- cloudflare points dns entry to public ip, no waf in between
- connected host points to the same dns entry
