### ISSUE TITLE
Usage of Gotify with Home Assistant

### ISSUE THREAD

**Issue by AussiSG** [gotify/server#806]
**Have you read the documentation?**
- [x] Yes, but it does not include related information regarding my question.

**You are setting up gotify in**
- [x] Docker

**Describe your problem**
Trying to a send a notification with an image attached in the preview pane to show on the android app.
Making use of the bigImageUrl part.
```
{
  "extras": {
    "client::notification": {
      "bigImageUrl": "https://placekitten.com/400/300"
    }
  }
}
```

I have setup the Gotify part in Home Assistant asfollowed:
```
# Gotify notify message with image
  - name: gotify_2
    platform: rest
    resource: !secret gotify_url
    method: POST_JSON
    headers: 
      X-Gotify-Key: !secret gotify_key
    message_param_name: message
    title_param_name: title
    data:
      extras:
        client::notification: 
          bigImageUrl: "https://placekitten.com/400/300"
```

And then trying to send a notification with Home Assistant with the following action:

```
action: notify.gotify_2
data:
  message: Test Image
  data:
    priority: 6
    extras:
      bigImageUrl: https://www.stickythings.nl/image/cache/catalog/muurstickers_biohazard/Biohazard-sticker-5-1000x1000.jpg
```

This does give me message with text but the picture shows some kind of grey icon thingy which is not the picture:

![Image](https://github.com/user-attachments/assets/c0621b69-26e1-486e-96d3-dc39fb0bfd58)

**Any errors, logs, or other information that might help us identify your problem**

**Comment by eternal-flame-AD** [comment]
Is there a particular documentation you are following to do this?

For general troubleshooting, can you try if your first JSON payload works if you send it to Gotify manually?

Then maybe something is being lost when passing through home assistant we can try figure it out more.

**Comment by AussiSG** [comment]
@eternal-flame-AD  Thank you for the reply,

I'm currently following the Home Assitant documentation:
https://www.home-assistant.io/integrations/notify.rest/

Could you tell me more about how to send it manually ?
I have been trying it with `curl` but no success. ( most like due to formatting )

**Comment by jmattheis** [comment]
Curl examples are here: https://gotify.net/docs/pushmsg

**Comment by AussiSG** [comment]
I found those. 
But using it as followed:
`curl -X POST "https://webpage.org/message?token=<token>" -F "title=my title" -F "message=my message" -F "bigimageurl=https://www.stickythings.nl/image/cache/catalog/muurstickers_biohazard/Biohazard-sticker-5-1000x1000.jpg"`

Only gives me the `my title` and `my message` in the notify

**Comment by jmattheis** [comment]
Ahh yeah, when using extras, you must use json. E.g.
```
curl --data '{"message": "message", "title": "mytitle", "priority":5, "extras": { "client::notification": { "bigImageUrl": "https://placekitten.com/400/300" } } } ' -H 'Content-Type: application/json' -H "X-Gotify-Key: Ao8WW754TGDWHXl" "http://localhost:8080/message"
```

**Comment by AussiSG** [comment]
When trying that line in my windows CMD it comes up with the following errors ?

```
curl: (3) URL rejected: Bad hostname
curl: (3) URL rejected: Port number was not a decimal number between 0 and 65535
curl: (3) URL rejected: Bad hostname
curl: (3) URL rejected: Port number was not a decimal number between 0 and 65535
curl: (3) URL rejected: Port number was not a decimal number between 0 and 65535
curl: (3) unmatched brace in URL position 1:
{
 ^
```

**Comment by eternal-flame-AD** [comment]
curl is aliased to powershell which has different syntax.

You can:

(1) Download a curl binary and run it, I heard in modern windows it comes with it and you can use it by just typing `curl.exe ...`, but if not there are many online tutorials to install it with details steps.
(2) Use WSL.
(3) Just use `Invoke-WebRequest` or `Invoke-RestMethod`, which what you are currently hitting, there are tutorials for that as well, just search keywords "POST json with XXX".

**Comment by AussiSG** [comment]
Thank you for the patience with this novice ............. :)

I 've download the Curl.exe and trying to use it with PowerShell. I get the following error:

```
PS C:\curl-8.14.1> curl.exe --data '{"message": "message", "title": "mytitle", "priority":5, "extras": { "client::notification": { "bigImageUrl": "https://picturewebpage.jpg" } } } ' -H 'Content-Type: application/json' -H "X-Gotify-Key: TOKEN" "https://url.gotify/message"
```
This is the error:
`{"error":"Bad Request","errorCode":400,"errorDescription":"invalid character 'm' looking for beginning of object key string"}`

**Comment by eternal-flame-AD** [comment]
This command looks normal to me, are you sure you typed this exact command? 

This seems to be the first double quote (") being missing in the data, this command looks to be correct (I also gave it a try in the Linux powershell distribution, it works).

**Comment by AussiSG** [comment]
I moved over to one of my LXC's to try it out... And there I could use the `curl `command properly ! 

So Used:
`curl --data '{"message": "message", "title": "mytitle", "priority":5, "extras": { "client::notification": { "bigImageUrl": "https://www.dulimex.nl/media/products/01600959015.jpg" } } } ' -H 'Content-Type: application/json' -H "X-Gotify-Key: AkyXvg5qbeeIMt." "http://localhost:8080/message"
`

This seems to be the output:
`{"id":26,"appid":2,"message":"message","title":"mytitle","priority":5,"extras":{"client::notification":{"bigImageUrl":"https://www.dulimex.nl/media/products/01600959015.jpg"}},"date":"2025-06-21T19:27:58.072369172Z"}`

But sadly enough the image is still similar as the one I posted in my first post

**Comment by jmattheis** [comment]
See your gotify/android logs.
```
2025-06-21 21:41:36.944 ERROR: Could not load image https://www.dulimex.nl/media/products/01600959015.jpg: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:358)
	at
```
The website provides an untrusted certificate. I get the same error when curling the image.
```
$ curl https://www.dulimex.nl/media/products/01600959015.jpg -H "User-agent: okhttp"
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the webpage mentioned above.
```

**Comment by AussiSG** [comment]
Holy chips you are right !
I've tried a picture taken of my doorbell which I exposed over my duckdns page.
That one works !

So I need to figure out what goes wrong when try to use the HomeAssisitant command.
Might be the declaration of the entity or the usage of it......

**Comment by AussiSG** [comment]
I am able to use this instruction in HomeAssistant to send a notify:
```
action: notify.gotify_2
data: {
    "title": "Hello World!",
    "message": "Hello from Home Assistant via Gotify"
}
```
But as soon as I add a row to the above command with any row from the one here down under, it fails.... :( 

```
  extras:
    client::notification: 
      bigImageUrl: 
```

It feels like HomeAssistant can not translate / understand this last part when being added

`"extras": { "client::notification": { "bigImageUrl": "https://url.doorbell.jpg" } }`

Or am I doing something completely wrong when trying to push an image in a notification like the example like this:

![Image](https://github.com/user-attachments/assets/6cac05e9-e52e-4086-9bed-79ab6fa1fc9c)

The red error says the following:
Action notify.gotify_2 could not be performed. extra keys not allowed @ data['bigImageUrl']. Got None

So It really feels like parsing/format/declaration thingy in HomeAssistant I guess :(
Hope you guys might see something in it. Also bear the first post how I declared the Notify entity within  HomeAssistant.

**Comment by jmattheis** [comment]
I don't think that the gotify fields are allowed there. You can sent in the dev tools test notifications.

![Image](https://github.com/user-attachments/assets/85498bf7-85f2-4ec1-861d-0a6026a81f12)

with this in the config

```
notify:
    - name: gotify_high
      platform: rest
      resource: http://192.168.178.2:8081/message
      method: POST_JSON
      headers:
        X-Gotify-Key: Ao8WW754TGDWHXl
      message_param_name: message
      title_param_name: title
      data:
        priority: 10
        extras:
          client::display:
            contentType: "text/markdown"
          client::notification:
            bigImageUrl: "https://http.cat/images/418.jpg"
```

Gotify seems to work fine, this seems more of a home assistant support request for which this project isn't the right place.

**Comment by AussiSG** [comment]
Indeed declaring it like that works. 
So your right that this feels like HomeAssistant isnt able to alternate the 
```
  client::notification:
    bigImageUrl: "https://http.cat/images/418.jpg"
```
Part in the data section. Alright will be heading to the HomeAssistant REST to request this I think

**Comment by AussiSG** [comment]
Issue closed, not an issue/problem with Gotify but the usage through Home Assitaant

**Comment by AussiSG** [comment]
Not giving up hehe.
I went over to use the REST command within home assistant with some templating. 
This seems to be working good aswell.

Here is the entity:
```
rest_command:
  gotify_doorbell:
    url: !secret gotify_url
    method: POST
    headers:
      Content-Type: application/json
      X-Gotify-Key: !secret gotify_key
    payload: '{"message": "message", "title": "mytitle", "priority":5, "extras": { "client::display": { "contentType": "text/plain"  }, "client::notification": { "bigImageUrl": "{{ image }}" , "click": {"url": "{{ url }}"} } } }'
```

And here is the usages of it:
```
action: rest_command.gotify_doorbell
data: {
  "message":"Berichtje",
  "mytitle":"Titel",
  "image":"https://http.cat/images/410.jpg",
  "url":"https://http.cat/images/420.jpg"
}
```

only thing is that I need to open up the notification to show the image. Or press the down arrow to show it in the preview section on my android phone. But I guess that's an Android thingy.

**Comment by AussiSG** [comment]
@jmattheis and @eternal-flame-AD ,

Do you have any thoughts why this is not being processed properly in/via home assistant to gotify?
Trying to send an image which I share via my Home Assistant server. 

But using the `!secret` part in the `message ` statements.

The message just shows the text ` ![] (!secret doorbell_test)`
As when using the direct URL instead of !secret , it works properly...

Rest command:
```
rest_command:
  gotify_doorbell:
    url: !secret gotify_url
    method: POST
    headers:
      Content-Type: application/json
      X-Gotify-Key: !secret gotify_key
    payload: '{"message": "{{ message }}", "title": "{{ mytitle}} ", "priority":5, "extras": { "client::display": { "contentType": "text/markdown"  }, "client::notification": { "bigImageUrl": "{{ image }}" , "click": {"url": "{{ url }}"} } } }'
```
Action:
```
action: rest_command.gotify_doorbell
data: 
  mytitle : "Test"
  message : "![] (!secret doorbell_test)" 
  image: "!secret doorbell_snapshot"
  url: "!secret doorbell_snapshot"
```

**Comment by jmattheis** [comment]
According to this you can't use !secret inline. https://community.home-assistant.io/t/using-secrets-in-a-path/16810

Maybe you could move this like this
```
action: rest_command.gotify_doorbell
data: 
  mytitle : "Test"
  message : "!secret doorbell_test" 
  ...
```
```
rest_command:
  gotify_doorbell:
    url: !secret gotify_url
    method: POST
    headers:
      Content-Type: application/json
      X-Gotify-Key: !secret gotify_key
    payload: '{"message": "![]({{ message }})", "title": "{{ mytitle}} ...."
```
or similar.
