### ISSUE TITLE
panic: pq: SSL is not enabled 

### ISSUE THREAD

**Issue by doronbehar** [gotify/server#90]
I get an error when running the server with the following configuration:

```yaml
server:
  port: 8001 # the port for the http server
  ssl:
    enabled: false # if https should be enabled
    redirecttohttps: true # redirect to https if site is accessed by http
    port: 8002 # the https port
    certfile: /etc/letsencrypt/live/doronbehar.com/fullchain.pem # the cert file (leave empty when using letsencrypt)
    certkey: /etc/letsencrypt/live/doronbehar.com/privkey.pem # the cert key (leave empty when using letsencrypt)
    letsencrypt:
      enabled: false # if the certificate should be requested from letsencrypt
      accepttos: false # if you accept the tos from letsencrypt
      cache: data/certs # the directory of the cache from letsencrypt
      hosts: # the hosts for which letsencrypt should request certificates
      - doronbehar.com
database: # for database see (configure database section)
  dialect: postgres
  connection: host=localhost port=5432 user=gotify dbname=gotify password=xxx

defaultuser: # on database creation, gotify creates an admin user
  name: admin # the username of the default user
  pass: admin # the password of the default user
passstrength: 10 # the bcrypt password strength (higher = better but also slower)
uploadedimagesdir: data/images # the directory for storing uploaded images
```

Error message:

```
Starting Gotify version 1.2.0@2018-11-24-11:06:13
Failed to find configuration config.yml
panic: pq: SSL is not enabled on the server

goroutine 1 [running]:
main.main()
        /home/travis/gopath/src/github.com/gotify/server/app.go:44 +0x425
```

The same error appears when enabling and disabling ssl.
